### ISSUE TITLE
python 2.7.16 h97142e2_2 ssl certificate validation broken due to incorrect paths

### ISSUE THREAD

**Issue by HarryWeppner** [ContinuumIO/anaconda-issues#11205]
### Actual Behavior

In an environment with `python 2.7.16 h97142e2_2` installed, ssl certificate verification fails 

```
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

### Expected Behavior

ssl certificate verification should not fail.

### Steps to Reproduce

1. `conda create -n foo python=2.7`
2. `conda activate foo`
3. create the following program as `ssl-tester.py`
```
#!/usr/bin/env python

try:
    import urllib2 #python2
except:
    import urllib.request as urllib2 #python3
import sys

req = urllib2.Request(sys.argv[1], headers={'User-Agent':'Mozilla/5.0'})
urllib2.urlopen(req)
```
4. run `ssl-tester.py` with an example url, e.g. `python ssl-tester.py https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/stopwords.zip`

I've root caused this further and it appears the package refers to incorrect `/opt/concourse/*` paths from the build, which are obviously not valid on my system. Here's a one-liner to verify:

```
$ python -c 'import ssl; print(ssl.get_default_verify_paths())'
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/opt/concourse/worker/volumes/live/10d9613e-ff14-49bc-7e0c-6735b93ba337/volume/python_1565715464570/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/opt/concourse/worker/volumes/live/10d9613e-ff14-49bc-7e0c-6735b93ba337/volume/python_1565715464570/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/ssl/certs')
```

##### Anaconda or Miniconda version:

`python 2.7.16 h97142e2_2`

##### `conda info`

<details>

```
     active environment : foo
    active env location : /usr/local/share/common/conda/envs/foo
            shell level : 2
       user config file : /Users/**************/.condarc
 populated config files : /Users/**************/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /usr/local/share/common/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/share/common/conda/pkgs
                          /Users/**************/.conda/pkgs
       envs directories : /usr/local/share/common/conda/envs
                          /Users/**************/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /usr/local/share/c3/conda/envs/foo:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py27_1    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1c               h1de35cc_1    defaults
pip                       19.1.1                   py27_0    defaults
python                    2.7.16               h97142e2_2    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                41.0.1                   py27_0    defaults
sqlite                    3.29.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
wheel                     0.33.4                   py27_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</details>

**Comment by mingwandroid** [comment]
Thank you for the bug report and useful research. I am looking into it now and can confirm the issue (and potentially another related but separate one).

**Comment by mingwandroid** [comment]
This is fixed in build #4. I also added a test to make sure this doesn't happen again.

Next week I hope to add automatic running of the full Python regression testsuite to all of our Python builds to prevent other mistakes such as this one.

Sorry again.

**Comment by HarryWeppner** [comment]
@mingwandroid  thanks for the quick turnaround - will test and verify on our side.

**Comment by mingwandroid** [comment]
Thank you.

**Comment by HarryWeppner** [comment]
@mingwandroid the paths look better now but it still isn't working out of the box as there is no `ssl` directory.

I believe this is due to a missing `ca-certificates` dependency:

```
$ conda create -n foo python=2.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/share/conda/envs/foo

  added / updated specs:
    - python=2.7


The following NEW packages will be INSTALLED:

  certifi            pkgs/main/osx-64::certifi-2019.6.16-py27_1
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  pip                pkgs/main/osx-64::pip-19.2.2-py27_0
  python             pkgs/main/osx-64::python-2.7.16-h97142e2_4
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-41.0.1-py27_0
  sqlite             pkgs/main/osx-64::sqlite-3.29.0-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.4-py27_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3
```

If you tried creating a Python 3.7 environment you'd see `ca-certificates` as a dependency.

**Comment by mingwandroid** [comment]
Gah, ok thanks, looking into it.

**Comment by jjhelmus** [comment]
`openssl` is not a dependency in the 2.7.16 packages which looks intentional.  Normally `openssl` pulls in `ca-certificates`.  It may be necessary to add a dependency on `ca-certificates` directly.

**Comment by mingwandroid** [comment]
Indeed. I'll do that now.

**Comment by HarryWeppner** [comment]
Thanks (again).

**Comment by mingwandroid** [comment]
Hi @HarryWeppner (and no problem).

Would it be possible for you to test my test packages on https://anaconda.org/rdonnelly? Python 2.7.16 build #5.

`conda create -n py2716_5 -c rdonnelly python=2.7.16`

Thanks!

**Comment by HarryWeppner** [comment]
@mingwandroid looks good - I just followed the steps in the description above and that works now!

**Comment by mingwandroid** [comment]
Phew! Thanks. I'm also progressing with improving our tests of Python 2 (and after I'll port that to Python 3). They're too important not to!

**Comment by HarryWeppner** [comment]
@mingwandroid it appears that these are also affected by the same issue. `3.6.6` is the most recent that is _not_ affected - haven't tested earlier versions.

```
python                         3.6.7      haf84260_0  pkgs/main
python                         3.6.8      haf84260_0  pkgs/main
python                         3.6.9      h359304d_0  pkgs/main
```

Do you think you can apply the same fix and push builds for these versions, too?

**Comment by mingwandroid** [comment]
Hey @HarryWeppner, this isn't something we would tend to do. We support only the latest 2 python 3 versions and the latest python 2 at present and do not normally revisit such old builds (even for the core interpreters).

I would be surprised though if it's the same issue since, to my mind, the bug was introduced very recently. Do you know which part is broken on these old builds? The first bit or the second? Or both?

Pinging @msarahan and @csoja in-case further action is needed here.

**Comment by HarryWeppner** [comment]
@mingwandroid ok, I am ok if we fix the latest Python version 3.6.9 quickly. The same instructions as I originally posted for Python 2.7 can be used to reproduce.

```bash
$ python -c 'import ssl; print(ssl.get_default_verify_paths())'
```
will yield some bogus paths that appear to come from the CI system?

**Comment by HarryWeppner** [comment]
We don't have the issue with the missing `ca-certificates` dependency but the first issue still exists.

**Comment by mingwandroid** [comment]
OK, can I ask that, for now at least, you build your own packages here? I can help guide you if necessary, no problem!
