### ISSUE TITLE
Anaconda-Navigator 1.3.2 not working on Mac OS X 10.12.1 (Sierra)

### ISSUE THREAD

**Issue by OrbitalMechanic** [ContinuumIO/anaconda-issues#1196]
I attempting to run Anaconda-Navigatoron 1.3.2 a Mac Pro running Mac OS X 10.12.1 (Sierra). Navigator appears to start up but subsequently crashes.

I've attached a copy of the crash report to this note.

Please advise.

[Anaconda-Navigator-dump.txt](https://github.com/ContinuumIO/anaconda-issues/files/554778/Anaconda-Navigator-dump.txt)

**Comment by mingwandroid** [comment]
Can you launch anaconda-navigator from an activated conda command prompt / console please?

It seems that an error message is being printed in the crash report (`pyqt5_err_print`) but because there's no console, the message is lost.

**Comment by OrbitalMechanic** [comment]
The message I get when I attempt to run anaconda navigator from a 
terminal window follows:

Samuels-Mac-Pro:~ user$ anaconda-navigator
/Users/user/anaconda/lib/python2.7/site-packages/clyent/__init__.py:10: 
UserWarning: Module argparse was already imported from 
/Users/user/anaconda/lib/python2.7/argparse.pyc, but 
/Users/user/anaconda/lib/python2.7/site-packages is being added to sys.path
   from pkg_resources import iter_entry_points
Traceback (most recent call last):
   File 
"/Users/user/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", 
line 355, in process_application_info
     packages, apps = output
TypeError: 'NoneType' object is not iterable
Abort trap: 6
Samuels-Mac-Pro:~ user$


Hope this helps.

Sam Dupree.

**Comment by louika** [comment]
After updating I face a similar issue on a mac os sierra vs. 10.12.1: 

```
mac:~ user$ anaconda-navigator

Traceback (most recent call last):
  File "/Applications/anaconda/bin/anaconda-navigator", line 4, in <module>
    import anaconda_navigator.app.main
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 20, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/__init__.py", line 20, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 33, in <module>
    from qtpy.QtCore import QObject, QThread, QTimer, Signal, QT_VERSION_STR
ImportError: cannot import name 'QT_VERSION_STR'
```

Here is conda info:
```
Current conda install:
               platform : osx-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.21.2
         python version : 3.5.1.final.0
       requests version : 2.10.0
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```

**Comment by mrveritas** [comment]
same issue here

**Comment by JuanCab** [comment]
Same issue here.  Can confirm running from the command line results in 

Traceback (most recent call last):
  File "/Users/????/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 355, in process_application_info
    packages, apps = output
TypeError: 'NoneType' object is not iterable
Abort trap: 6

**Comment by goanpeca** [comment]
@JuanCab this has been fixed and will be release with the next version. Sorry for the inconveniences

**Comment by OrbitalMechanic** [comment]
When will we see the next version of Anaconda-navigator with the fix installed?

**Comment by goanpeca** [comment]
if you are seeing the same qt error you can try updating the qtpy package.

Could you try

`conda update qtpy`

**Comment by jwjwj** [comment]
Same issue. (Tried to updated qty as above, but already up-to-date). When running anaconda-navigator, here is the Python error message:

Env: MacOS 10.12.2 (beta), Anaconda3-4.2.0-MacOSX-x86_64

```
machineName userName$ anaconda-navigator 
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 70, in main
    window = run_app(splash)
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 38, in run_app
    window = MainWindow(splash=splash)
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 145, in __init__
    self.api = AnacondaAPI()
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 434, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 39, in __init__
    self._conda_api = CondaAPI()
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1185, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 267, in __init__
    self.set_root_prefix()
  File "/Users/userName/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 374, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```
TIA

**Comment by goanpeca** [comment]
@jwjwj could you open a terminal and type

`$ conda info` 

And paste the results here, and then type

`$ Conda list`

and paste the results here again.

Thanks

**Comment by JuanCab** [comment]
Still crashing as of today.  Here's the conda info and on screen feedback:

[UserName@MyMacName:~ 10:44]$ conda update qtpy
Fetching package metadata ...................
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /Users/UserName/anaconda3:
#
qtpy                      1.1.2                    py35_0    defaults
[UserName@MyMacName:~ 10:44]$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 3.5.1.final.0
       requests version : 2.12.4
       root environment : /Users/UserName/anaconda3  (writable)
    default environment : /Users/UserName/anaconda3
       envs directories : /Users/UserName/anaconda3/envs
          package cache : /Users/UserName/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://ssb.stsci.edu/astroconda/osx-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://conda.anaconda.org/astropy/osx-64
                          https://conda.anaconda.org/astropy/noarch
                          https://conda.anaconda.org/mwcraig/osx-64
                          https://conda.anaconda.org/mwcraig/noarch
                          https://conda.anaconda.org/coursera/osx-64
                          https://conda.anaconda.org/coursera/noarch
                          https://conda.anaconda.org/auto/osx-64
                          https://conda.anaconda.org/auto/noarch
            config file : /Users/UserName/.condarc
           offline mode : False

[UserName@MyMacName:~ 10:45]$ anaconda-navigator
INFO navigator:setup(42): Setting up logger
DEBUG navigator:start(233): conda info --json
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3/envs/py27')
DEBUG navigator:get_envs(399):
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3/envs/py27')
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3')
DEBUG navigator:linked(427): /Users/UserName/anaconda3
DEBUG navigator:get_envs(399):
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3/envs/py27')
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3')
DEBUG navigator:linked(427): /Users/UserName/anaconda3
DEBUG navigator:get_envs(399):
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3/envs/py27')
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3')
DEBUG navigator:linked(427): /Users/UserName/anaconda3
DEBUG navigator:get_envs(399):
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3/envs/py27')
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3')
DEBUG navigator:linked(427): /Users/UserName/anaconda3
DEBUG navigator:set_domain(355): https://api.anaconda.org
DEBUG navigator:set_domain(355): https://api.anaconda.org
DEBUG navigator:download(225): ('https://repo.continuum.io/pkgs/metadata.json', '/Users/UserName/.anaconda/navigator/channels/metadata.json', False)
DEBUG navigator:is_valid_url(238): https://repo.continuum.io/pkgs/pro/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): http://ssb.stsci.edu/astroconda/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://conda.anaconda.org/astropy/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://conda.anaconda.org/mwcraig/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://conda.anaconda.org/coursera/osx-64/repodata.json.bz2
DEBUG navigator:is_valid_url(238): https://conda.anaconda.org/auto/osx-64/repodata.json.bz2
DEBUG navigator:download(225): ('https://repo.continuum.io/pkgs/pro/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_pro_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_free_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('http://ssb.stsci.edu/astroconda/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/ssb.stsci.edu_astroconda_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://conda.anaconda.org/coursera/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_coursera_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://conda.anaconda.org/mwcraig/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_mwcraig_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://conda.anaconda.org/astropy/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_astropy_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://conda.anaconda.org/conda-forge/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_conda-forge_osx-64_repodata.json.bz2', False)
DEBUG navigator:download(225): ('https://conda.anaconda.org/auto/osx-64/repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_auto_osx-64_repodata.json.bz2', False)
DEBUG navigator:environment_exists(914): (None, '/Users/UserName/anaconda3')
DEBUG navigator:linked(427): /Users/UserName/anaconda3
DEBUG navigator:load_repodata(343): ['/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_auto_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/ssb.stsci.edu_astroconda_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_pro_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_astropy_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_mwcraig_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_free_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_coursera_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_conda-forge_osx-64_repodata.json.bz2']
DEBUG navigator:load_repodata(343): ['/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_auto_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/ssb.stsci.edu_astroconda_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_pro_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_astropy_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_mwcraig_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/repo.continuum.io_pkgs_free_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_coursera_osx-64_repodata.json.bz2', '/Users/UserName/.anaconda/navigator/channels/conda.anaconda.org_conda-forge_osx-64_repodata.json.bz2']
DEBUG navigator:start(58): ('anaconda_navigator.api.client_api', '_load_repodata', NotFound('The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.', 404))
ERROR navigator:process_application_info(353): 'The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.', 404
Traceback (most recent call last):
  File "/Users/UserName/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 355, in process_application_info
    packages, apps = output
TypeError: 'NoneType' object is not iterable
Abort trap: 6

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by misc1611** [comment]
Hi there,
I've just tried running the latest version of Anaconda Navigator (downloaded from Continuum today) on macOS Sierra (10.12.3) and seem to be encountering the same issue as others here have described - the app tried loading for about 5 or 10 seconds and then crashes.

It seems the problem still exists, sorry.

**Comment by mattstone** [comment]
OSX Sierra 10.12.1 crashing on startup here as well

matt$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/matt/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.6.0 Darwin/16.1.0 OSX/10.12.1
                UID:GID : 501:20



matt$ Conda list
# packages in environment at /Applications/anaconda:
#
_license                  1.1                      py36_1  
alabaster                 0.7.9                    py36_0  
anaconda                  4.3.0               np111py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.4.3                    py36_0  
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0               np111py36_0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
chest                     0.2.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.7                    py36_0  
conda                     4.3.9                    py36_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py36_0  
contextlib2               0.5.4                    py36_0  
cryptography              1.7.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.13.0                   py36_0  
datashape                 0.5.4                    py36_0  
decorator                 4.0.11                   py36_0  
dill                      0.2.5                    py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_0  
et_xmlfile                1.0.1                    py36_0  
fastcache                 1.0.2                    py36_1  
flask                     0.12                     py36_0  
flask-cors                3.0.2                    py36_0  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
greenlet                  0.4.11                   py36_0  
h5py                      2.6.0               np111py36_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
icu                       54.1                          0  
idna                      2.2                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.1.0                    py36_1  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.9.0                    py36_1  
jinja2                    2.9.4                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console           5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.2                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.0               np111py36_0  
mistune                   0.7.3                    py36_1  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
multipledispatch          0.4.9                    py36_0  
nbconvert                 4.2.0                    py36_0  
nbformat                  4.2.0                    py36_0  
networkx                  1.11                     py36_0  
nltk                      3.2.2                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  4.3.1                    py36_0  
numba                     0.30.1              np111py36_0  
numexpr                   2.6.1               np111py36_2  
numpy                     1.11.3                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
openpyxl                  2.4.1                    py36_0  
openssl                   1.0.2k                        0  
pandas                    0.19.2              np111py36_1  
partd                     0.3.7                    py36_0  
path.py                   10.0                     py36_0  
pathlib2                  2.2.0                    py36_0  
patsy                     0.4.1                    py36_0  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.0.0                    py36_0  
pip                       9.0.1                    py36_1  
ply                       3.9                      py36_0  
prompt_toolkit            1.0.9                    py36_0  
psutil                    5.0.1                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.32                   py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.1.3                    py36_0  
pylint                    1.6.4                    py36_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_1  
pytables                  3.3.0               np111py36_0  
pytest                    3.0.5                    py36_0  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
pytz                      2016.10                  py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         0  
qtawesome                 0.4.3                    py36_0  
qtconsole                 4.2.1                    py36_1  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py36_0  
requests                  2.12.4                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.12.3              np111py36_1  
scikit-learn              0.18.1              np111py36_1  
scipy                     0.18.1              np111py36_1  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sockjs-tornado            1.0.3                    py36_0  
sphinx                    1.5.1                    py36_0  
spyder                    3.1.2                    py36_0  
sqlalchemy                1.1.5                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py36_1  
sympy                     1.0                      py36_0  
terminado                 0.6                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.1                    py36_0  
unicodecsv                0.14.1                   py36_0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.11.15                  py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        1.2.6                    py36_0  
wrapt                     1.10.8                   py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.2                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
matt$

**Comment by DrDeji** [comment]
The anaconda navigator doesn't work on my mac OSX Yosemite-getting the following error:

ImportError: cannot import name QKeySequence

**Comment by DeanDro** [comment]
I have the same issue with OSX 10.10 Yosemite. Anaconda is keep crushing

**Comment by goanpeca** [comment]
Please run on the terminal

`sudo rm -rf ~/.continuum`

**Comment by DrDeji** [comment]
@goanpeca, does that not remove the anaconda installation? Anything I need to be aware of?

**Comment by goanpeca** [comment]
>does that not remove the anaconda installation?

No it does not. It just removes some config file on a folder that has the wrong permissions.

**Comment by DrDeji** [comment]
@goanpeca, tried `sudo rm -rf ~/.continuum` and then attempted launching anaconda-navigator from the terminal-it gave the following error:

ImportError: dlopen(/.../.../anaconda/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: @rpath/libpng16.16.dylib

Referenced from: /.../.../anaconda/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0

**Comment by goanpeca** [comment]
@DrDeji Navigator works with Qt5 and PyQt5 so you must have a corrupted environment.

I would advice to reinstall the latest anaconda distribution from scratch

**Comment by goanpeca** [comment]
I am locking this conversation cause many users keep reporting an issue that does not correspond to the original problem
