### ISSUE TITLE
Anaconda update breaks KDE if it's added to PATH

### ISSUE THREAD

**Issue by awehrfritz** [ContinuumIO/anaconda-issues#1206]
After updating anaconda (in particular the switch from qt4 to qt5), I'm not able to login to my KDE desktop anymore. After entering my password, a X-window pops up saying:
"Could not start D-bus. Can you call qdbus-qt5?"

A workaround is to simply comment out the line in .bashrc that adds anaconda to the path, but obviously anaconda is then not usable anymore.

If it is really necessary that anaconda ships it's own version of the qt5 libraries, then you should make sure that these libraries and programs don't take precedence over the system libraries for anything else but anaconda.

This issue has also been discussed in the openSUSE forums:
https://forums.opensuse.org/showthread.php/520628-Could-not-start-D-bus-Can-you-call-qdbus-qt5

My system:
openSUSE Leap 42.1 (x86_64)
Qt 5.5.1 (built against 5.5.1)
KDE Frameworks 5.21.0

`conda info`:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.20.0
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/user/anaconda2  (writable)
    default environment : /home/user/anaconda2
       envs directories : /home/user/anaconda2/envs
          package cache : /home/user/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

**Comment by ccordoba12** [comment]
What if you create a symlink to Anaconda `qdbus` in `~/anaconda/bin` called `qdbus-qt5`? That solves the problem for you?

**Comment by ccordoba12** [comment]
Could you ask in the Open Suse forums if the solution is for us to remove `qtpaths`? Thanks!

**Comment by ccordoba12** [comment]
> you should make sure that these libraries and programs don't take precedence over the system libraries for anything else but anaconda.

We leave that decision to users in our installer.

**Comment by mingwandroid** [comment]
> If it is really necessary that anaconda ships it's own version of the qt5 libraries, then you should make sure that these libraries and programs don't take precedence over the system libraries for anything else but anaconda.

It is really necessary, yes. Binary compatibility requires that we build these things and we cannot use the distro supplied versions in general because the distros are all too different, i.e. if we were to compile PyQt against SUSE linux's Qt5 libraries, then that PyQt would not work on CentOS, Fedora, Ubuntu or Debian (in fact it would likely only work on the SUSE linux that we compiled it against).

**Comment by mingwandroid** [comment]
In this case, SUSE should not run an arbitrary `qtpaths`, instead, as these are system packages that know exactly where they should live, it should run explicitly `/usr/bin/qtpaths`.

**Comment by awehrfritz** [comment]
Thanks for the quick response!

I tested removing `qtpaths` from `~/anaconda2/bin` and this fixes the problem. In fact, I consider this a rather clean solution, as I assume that anaconda packages only require the qt libraries and never utilize `qtpaths`. The further, since only `~/anaconda2/bin` is added to PATH and no lib directory to LD_LIBRARY_PATH, the Qt libraries from anaconda don't take precedence over the system libraries otherwise.
To be clear, I tested the login to KDE as well as anaconda, i.e. I generated a simple plot using `matplotlib` with the `Qt5Agg` backend.

**Comment by awehrfritz** [comment]
@ccordoba12 I am aware of the fact that this issue only occurs if anaconda is in PATH, but I would say that that's the standard case for most anaconda users, hence I consider this relevant to a wide user base.

**Comment by mingwandroid** [comment]
`qtpaths` is useful for people who want to develop software using the conda Qt package. The bug lies in openSUSE somewhere as it should explicitly reference `/usr/bin/qtpaths` (because the software knows that is where the `qtpaths` that it wants is located) and not just use the first one found in `PATH`.

Personally, I do not recommend anyone adding a non-system software distribution to their system PATH. It is much more sensible to change environment in a more localized, deliberate way.

**Comment by awehrfritz** [comment]
> > If it is really necessary that anaconda ships it's own version of the qt5 libraries ..

> It is really necessary, yes. ...

Fair enough! I see your point regarding the various versions of Qt shipped for various distributions and operating systems.

@mingwandroid, I will bring up your suggestion to run `/usr/bin/qtpaths` instead of `qtpaths` in the openSUSE forums. Maybe they will come up with a fix.

**Comment by mingwandroid** [comment]
Thanks, I'd like to know what the resolution is.

**Comment by awehrfritz** [comment]
> Personally, I do not recommend anyone adding a non-system software distribution to their system PATH. It is much more sensible to change environment in a more localized, deliberate way.

Well, this might be a good way for an occasional python user, but certainly not for an advanced user.
I personally use python (and the anaconda distribution) extensively and have dozens of terminal windows with various ipython sessions open during a regular workday. My workflow would be seriously disturbed if I was to add manually anaconda to PATH every time I start a new session.

**Comment by mingwandroid** [comment]
I am not suggesting manually typing `export PATH=` (or better `<CONDA_INSTALL_LOCATION>/bin/activate root`) each time you want to use Anaconda Python. I use a shell script that takes very few characters to source (e.g. `. ~/mc`). I could also call that from a `.desktop` file to allow launching it from a desktop launcher but I haven't bothered to do that yet.

**Comment by ccordoba12** [comment]
@mingwandroid, what about renaming our `qtpaths` to `qtpaths-qt5`?

**Comment by mingwandroid** [comment]
I'll do that if we have to.

**Comment by awehrfritz** [comment]
The openSUSE developers agreed to add the absolute path to the places where `qtpaths` is invoked, this should fix the problem.
Though I should not that the openSUSE developers were not too happy with this solution either, so this may come up again some day. Anyway, here the link to the discussion with the openSUSE developer:
https://forums.opensuse.org/showthread.php/520628-Could-not-start-D-bus-Can-you-call-qdbus-qt5?p=2798385#post2798385

**Comment by duckdodger** [comment]
I'd like to point out that this issue is not exactly because of openSUSE but rather it's KDE. KDE Plasma uses a `startkde` script for starting Plasma which looks for the first instance of qtpaths in PATH, so it finds the Anaconda version of qtpaths and loads it.
Then it looks for `qdbus-qt5` (which is how `qdbus` is named in openSUSE to avoid conflict with the qt4 version) in the path set by `qtpaths` but it fails to find it because that's not how `qdbus` is named in Anaconda and throws an error.

So the patch that is being applied by openSUSE to hardcode the path to qtpaths in `startkde` is just a workaround. Their opinion is that it can't be fixed upstream (that is, by KDE) either because qtpaths is a way for Plasma to be independent of where the Qt5 libraries are installed (which is kinda ironic), that is, someone may choose to install Qt5 elsewhere other than `/usr/bin`. 

Also, if `qtpaths` is used by something else, that also has the potential to break due to not finding the right qt5.

**Comment by msarahan** [comment]
@LeonhardtAndreas that is actually an excellent improvement in my opinion, and I'll recommend internally that we add this to our installers.

**Comment by mingwandroid** [comment]
> since I use Anaconda from the terminal only

but what about people who use it for all their software needs? We're moving away from recommending modifying PATH (or even setting it at all) and having `conda` as a shell function anyway aren't we?

**Comment by doutriaux1** [comment]
@durack1 the newer way to do things in conda is to have **nothing** added in PATH, instead it sources a special bash file that defines a `conda` function. Of course you're not going to like like because it means no tcsh for you 😉

**Comment by durack1** [comment]
@doutriaux1 got a link describing this new way?

**Comment by mingwandroid** [comment]
> I would advocate it gets moved after a number of the system paths are defined

That won't work either. Instead of your distro software not working, now `Anaconda Distribution` software will not work. @kalefranz do you have a good reference for the new way?

**Comment by durack1** [comment]
So other folks don't pull their hair out as long as I did, here are the errors contained in the vnc log for the two environments (which can be switched by creating/editing the `~/.Xclients` file, e.g. below):
GNOME2:
```
[duro@ocean ~/.vnc]$ more ~/.vnc/machineName:1.log
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

Xvnc TigerVNC 1.7.1 - built Jan 19 2017 18:38:20
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11704000, The X.Org Foundation

Tue May  1 13:44:32 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
gnome-session[11015]: WARNING: Could not make bus activated clients aware of DISPLAY=:1 environment variable: Failed to connect to socket /tmp/dbus-CrmwEz22xX: Connection refused
gnome-session[11015]: WARNING: Could not make bus activated clients aware of GNOME_DESKTOP_SESSION_ID=this-is-deprecated environment variable: Failed to connect to socket /tmp/dbus-
CrmwEz22xX: Connection refused
gnome-session[11015]: WARNING: Could not make bus activated clients aware of SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/11015,unix/unix:/tmp/.ICE-unix/11015 environment variable: Fa
iled to connect to socket /tmp/dbus-CrmwEz22xX: Connection refused
```
And on the login screen when trying to connect using a vnc client:
```
Could not connect to session bus: Failed to connect to socket /tmp/dbus-a46yWcaPVt: Connection refused
```
Switch from redhat default GNOME to KDE:
```
[duro@ocean ~]$ more .Xclients
#exec startx ; # In theory this reverts to GNOME
exec startkde ; # KDE shell
```
And KDE:
```
[duro@ocean ~/.vnc]$ more ~/.vnc/machineName:1.log
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

Xvnc TigerVNC 1.7.1 - built Jan 19 2017 18:38:20
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11704000, The X.Org Foundation

Tue May  1 13:47:28 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
startkde: Starting up...
startkde: Could not start D-Bus. Can you call qdbus?
```

**Comment by doutriaux1** [comment]
@durack1 for example see: https://stackoverflow.com/questions/47246350/conda-activate-not-working?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

but the nitty gritty is the following message on newer conda:
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". ~/anaconda/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s ~/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="~/anaconda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^
```

**Comment by durack1** [comment]
@dnadeau4 ping

**Comment by zeus86** [comment]
Thanks for debugging this, this really helped me out today. 

One further note: 
You should pay attention to this issue, when e.G. spawning a second X from a getty.
While a login-manager starts a KDE just fine, it will still fail in this context, when trying to spawn a second X from a getty-terminal or so manually, because this would be an interactive terminal.

**Comment by stiv-yakovenko** [comment]
This problem should be fixed somehow. I lost 2 hours searching for this thread. Miniconda, please, if you can't fix it at least notify about the problem in the install script if xrdp is installed on the system.

**Comment by awehrfritz** [comment]
This is a pretty nasty issue that comes up every now and then and I am surprised no Anaconda developer wants to fix this. Anyway, I nowadays use Fedora/KDE and work around this issue in a rather elegant way using [Environment Modules](http://modules.sourceforge.net/). :smiley:

This works very well once you have your module file created, which is again a pain in the neck since the Anaconda developers use such a cumbersome init process. However, this has the clear upside of 1) not having to fiddle around with the overly complex Anaconda init procedure and 2) being able to add and remove anaconda reliably from the `PATH` at any time.

To generate the module file, I first install Anaconda the usual way via the installer which adds a section to the end of my `.bashrc`. I then use the following script to extract that section and run it through the [createmodule.sh](https://github.com/cea-hpc/modules/blob/master/contrib/scripts/createmodule.sh) script which generates a module file:
``` bash
# Extract the lines added by the Anaconda installer from the bashrc file
grep -A1000 "# added by Anaconda" ~/.bashrc > anaconda3_init.sh
sed '/# added by Anaconda/,$d' -i ~/.bashrc

# Create a modulefile based on the Anaconda init file
createmodule.sh ./anaconda3_init.sh > ./anaconda3_modulefile
```
In my case, this yields a module file which looks like this:
``` sh
#%Module 1.0
prepend-path	PATH	/path/to/anaconda3/bin
setenv		CONDA_DEFAULT_ENV	base
setenv		CONDA_EXE	/path/to/anaconda3/bin/conda
setenv		CONDA_PREFIX	/path/to/anaconda3
setenv		CONDA_PROMPT_MODIFIER
setenv		CONDA_PYTHON_EXE	/path/to/anaconda3/bin/python
setenv		CONDA_SHLVL	1
```
This module file needs to be put to the Environment Modules search path (e.g. `~/.local/share/modulefiles/`):
``` sh
mkdir -p ~/.local/share/modulefiles/python/
cp ./anaconda3_modulefile ~/.local/share/modulefiles/python/anaconda3
```
My .bashrc looks then like this:
``` bash
module use -a ~/.local/share/modulefiles/
module load python/anaconda3
```
To remove Anaconda from the `PATH`, simply do:
``` bash
module unload python/anaconda3
```

Not really a fix to the issue, but a rather elegant, and more importantly reliable, workaround. Hope this is of help for some people.

**Comment by kakopedreros** [comment]
> My workaround is to check if I am in an interactive shell before including the Anaconda path in the bashrc, since I use Anaconda from the terminal only. The test can be done by checking for a prompt variable by adding the two lines around the `export` statement:
> 
> ```
> if [ ! -z $PS1 ]; then
>     export PATH="<path-to-anaconda-bin>:$PATH"
> fi
> ```
> 
> or by testing for `i` in `$-`.

Hi, looking for help regarding this matter 

Taking the experience from this issue:
https://github.com/neutrinolabs/xrdp/issues/1346#issuecomment-540994732

I apply the command sudo chmod +x to the file /opt/anaconda/bin/conda.

Also, i modify the .bashrc file with breaking Anaconda in the terminal and the remote desktop.

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    if [ "${PS1-}" ]; then
        eval "$__conda_setup"
    fi
#else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by maacruz** [comment]
This issue is back on OpenSUSE Leap 15.6 (KDE Plasma 5.27.11).
Login is possible but OpenGL acceleration in the desktop is broken, which brings in various graphical glitches unless compositing is deactivated.
To fixit I had to add a check for an interactive shell both at the eval and PATH lines.

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]&&[ "${PS1-}" ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        if [ "${PS1-}" ]; then
            export PATH="/opt/anaconda/bin:$PATH"
        fi
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

```
