### ISSUE TITLE
navigator causing segfault

### ISSUE THREAD

**Issue by stefanseefeld** [ContinuumIO/anaconda-issues#1255]
Trying to run `navigator` I get this error:

```
$ /usr/local/CA/anaconda3/bin/anaconda-navigator 
Traceback (most recent call last):
  File "/usr/local/CA/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 72, in main
    window = run_app(splash)
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 40, in run_app
    window = MainWindow(splash=splash)
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 145, in __init__
    self.api = AnacondaAPI()
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 434, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 39, in __init__
    self._conda_api = CondaAPI()
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1185, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 267, in __init__
    self.set_root_prefix()
  File "/usr/local/CA/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 374, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
Segmentation fault (core dumped)
```

This is version 1.3.2-py35_0.

**Comment by goanpeca** [comment]
Hi @stefanseefeld, the new version will fix this problem and is coming out next week. Sorry fo the trouble

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by VessoVit** [comment]
I still have the issue with 1.4.3

**Comment by DmitriyLanchakov** [comment]
localhost:~ # conda install anaconda-navigator
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /root/anaconda3:
#
anaconda-navigator        1.4.3                    py36_0
localhost:~ # anaconda-navigator
Traceback (most recent call last):
  File "/root/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 711, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 49, in __init__
    self._conda_api = CondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/root/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by nseetim** [comment]
I still have the issue with 1.5.3
It's really not nice downloading a software that large that doesn't work

**Comment by nseetim** [comment]
error report
Traceback (most recent call last):
  File "./anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 718, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 50, in __init__
    self._conda_api = CondaAPI()
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1302, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 307, in __init__
    self.set_root_prefix()
  File "/root/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 427, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
Segmentation fault

**Comment by Koriolisah** [comment]
I still have this issue 1.6.3

**Comment by nseetim** [comment]
is there a new, stable and working release of anaconda we can use

**Comment by nseetim** [comment]
I installed anaconda yesterday and it's working fine, try installing
following the guide on the official anaconda site exactly
