### ISSUE TITLE
Alembic 1.7.4 missing dependencies for Python <3.9

### ISSUE THREAD

**Issue by tvoipio** [ContinuumIO/anaconda-issues#12705]
It seems that Alembic 1.7.4 package is missing a dependency. Please compare `setup.cfg` at https://github.com/sqlalchemy/alembic/blob/rel_1_7_4/setup.cfg#L42 and `index.json` of the package installed from from pkgs/main:

<details>

```{
  "arch": null,
  "build": "pyhd3eb1b0_0",
  "build_number": 0,
  "depends": [
    "mako",
    "python >=3.6",
    "python-dateutil",
    "python-editor >=0.3",
    "sqlalchemy >=1.3.0"
  ],
  "license": "MIT",
  "license_family": "MIT",
  "name": "alembic",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1633989481947,
  "version": "1.7.4"
}
```

</details>

Note that importlib_metadata and importlib_resources are missing from `depends`.

### Actual Behavior

Installing `alembic` 1.7.4 from pkgs/main does not install `importlib_resources`, causing import error when actually trying to use Alembic.

`conda install importlib_resources` seems to fix the issue.

### Expected Behavior

Installing Alembic automatically installs `importlib_resources` for Python versions 3.6-3.8

### Steps to Reproduce

1. Start with a fresh environment, Python 3.7 (Anaconda 2019.03 in our case)
2. `conda install alembic` (or `conda install alembic=1.7.4`
3. `python -c "import alembic"` results in `ModuleNotFoundError: No module named 'importlib_resources'`

##### Anaconda or Miniconda version:

`alembic                   1.7.4              pyhd3eb1b0_0`

##### Operating System:

Linux, Ubuntu 18.04; `5.4.0-1059-aws #62~18.04.1-Ubuntu SMP Fri Oct 22 21:51:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

##### `conda info`

<details>

```
     active environment : minerva_ng
    active env location : /home/analytics_user/anaconda3/envs/minerva_ng
            shell level : 2
       user config file : /home/analytics_user/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/analytics_user/anaconda3  (writable)
      conda av data dir : /home/analytics_user/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/analytics_user/anaconda3/pkgs
                          /home/analytics_user/.conda/pkgs
       envs directories : /home/analytics_user/anaconda3/envs
                          /home/analytics_user/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.21.0 CPython/3.7.3 Linux/5.4.0-1059-aws ubuntu/18.04 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /home/analytics_user/anaconda3/envs/minerva_ng:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
aiobotocore               1.4.1              pyhd3eb1b0_0    defaults
aiohttp                   3.7.4.post0      py37h7f8727e_2    defaults
aioitertools              0.7.1              pyhd3eb1b0_0    defaults
alembic                   1.7.4              pyhd3eb1b0_0    defaults
argcomplete               1.12.3             pyhd3eb1b0_0    defaults
argon2-cffi               20.1.0           py37h27cfd23_1    defaults
arrow-cpp                 4.0.1            py37hced866c_3    defaults
arviz                     0.11.4             pyhd8ed1ab_0    conda-forge
asn1crypto                1.4.0                      py_0    defaults
async-timeout             3.0.1            py37h06a4308_0    defaults
async_generator           1.10             py37h28b3542_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
autopage                  0.4.0              pyhd8ed1ab_0    conda-forge
aws-c-common              0.4.57               he6710b0_1    defaults
aws-c-event-stream        0.1.6                h2531618_5    defaults
aws-checksums             0.1.9                he6710b0_0    defaults
aws-sdk-cpp               1.8.185              hce553d0_0    defaults
azure-common              1.1.27             pyhd3eb1b0_0    defaults
azure-core                1.14.0             pyhd3eb1b0_0    defaults
azure-storage-blob        12.9.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
binutils_impl_linux-64    2.33.1               he6710b0_7    defaults
binutils_linux-64         2.33.1              h9595d00_15    conda-forge
black                     21.10b0            pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
blinker                   1.4              py37h06a4308_0    defaults
boost-cpp                 1.73.0              h27cfd23_11    defaults
boto3                     1.17.105           pyhd3eb1b0_0    defaults
botocore                  1.20.106           pyhd3eb1b0_0    defaults
bottleneck                1.3.2            py37heb32a55_1    defaults
brotli                    1.0.9                he6710b0_2    defaults
brotlipy                  0.7.0           py37h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.17.1               h27cfd23_0    defaults
ca-certificates           2021.10.26           h06a4308_2    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
certifi                   2021.10.8        py37h06a4308_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
cftime                    1.5.0            py37h6323ea4_0    defaults
chardet                   4.0.0           py37h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.3              pyhd3eb1b0_0    defaults
cliff                     3.9.0              pyhd8ed1ab_0    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
cmaes                     0.8.2              pyh44b312d_0    conda-forge
cmd2                      2.2.0            py37h89c1867_0    conda-forge
cmdstanpy                 0.9.68             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyhd3eb1b0_0    defaults
colorlog                  5.0.1            py37h06a4308_1    defaults
convertdate               2.3.2              pyhd3eb1b0_0    defaults
cryptography              3.4.8            py37hd23ed53_0    defaults
curl                      7.78.0               h1ccaba5_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.24          py37h295c915_0    defaults
dataclasses               0.8                pyh6d0b6a4_7    defaults
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.4.1            py37h295c915_0    defaults
decorator                 5.1.0              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
dill                      0.3.4              pyhd3eb1b0_0    defaults
double-conversion         3.1.5                he6710b0_1    defaults
entrypoints               0.3                      py37_0    defaults
ephem                     4.0.0.2          py37h27cfd23_0    defaults
et_xmlfile                1.1.0            py37h06a4308_0    defaults
expat                     2.4.1                h2531618_2    defaults
fastprogress              1.0.0              pyhb85f177_0    defaults
filelock                  3.3.1              pyhd3eb1b0_1    defaults
flake8                    4.0.1              pyhd8ed1ab_1    conda-forge
fontconfig                2.13.1               h6c09931_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.11.0               h70c0345_0    defaults
fsspec                    2021.8.1           pyhd3eb1b0_0    defaults
gcc_impl_linux-64         7.3.0                habb00fd_1    defaults
gcc_linux-64              7.3.0               h553295d_15    conda-forge
gflags                    2.2.2                he6710b0_0    defaults
giflib                    5.2.1                h7b6447c_0    defaults
glib                      2.63.1               h5a9c865_0    defaults
glog                      0.5.0                h2531618_0    defaults
gmp                       6.2.1                h2531618_2    defaults
grpc-cpp                  1.26.0               hf8bcb03_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
gurobi                    9.1.2                    py37_0    gurobi
gxx_impl_linux-64         7.3.0                hdf63c60_1    defaults
gxx_linux-64              7.3.0               h553295d_15    conda-forge
hdf4                      4.2.13               h3ca952b_2    defaults
hdf5                      1.10.6               hb1b8bf9_0    defaults
hijri-converter           2.2.2              pyhd3eb1b0_0    defaults
holidays                  0.11.3.1           pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.2                pyhd3eb1b0_0    defaults
imbalanced-learn          0.8.1                    pypi_0    pypi
importlib-metadata        3.10.0           py37h06a4308_0    defaults
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
ipykernel                 6.4.1            py37h06a4308_1    defaults
ipython                   7.29.0           py37hb070fc8_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
isodate                   0.6.0              pyhd3eb1b0_1    defaults
jdcal                     1.4.1              pyhd3eb1b0_0    defaults
jedi                      0.18.0           py37h06a4308_1    defaults
jinja2                    3.0.2              pyhd3eb1b0_0    defaults
jmespath                  0.10.0             pyhd3eb1b0_0    defaults
joblib                    1.1.0              pyhd3eb1b0_0    defaults
jpeg                      9d                   h7f8727e_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_client            7.0.1              pyhd3eb1b0_0    defaults
jupyter_core              4.8.1            py37h06a4308_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kiwisolver                1.3.1            py37h2531618_0    defaults
korean_lunar_calendar     0.2.1              pyhd3eb1b0_0    defaults
krb5                      1.19.2               hac12032_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libboost                  1.73.0              h3ff78a5_11    defaults
libcurl                   7.78.0               h0b77cf5_0    defaults
libedit                   3.1.20210714         h7f8727e_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libevent                  2.1.8                h1ba5d50_1    defaults
libffi                    3.2.1             hf484d3e_1007    defaults
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   11.2.0              h1d223b6_11    conda-forge
libllvm11                 11.1.0               h3826bc1_0    defaults
libnetcdf                 4.6.1                h2053bdc_4    defaults
libnghttp2                1.41.0               hf8bcb03_2    defaults
libpng                    1.6.37               hbc83047_0    defaults
libprotobuf               3.11.2               hd408876_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libthrift                 0.13.0               hfb8234f_6    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
libwebp                   1.2.0                h89dd481_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxgboost                1.5.0                h9c3ff4c_0    conda-forge
libxml2                   2.9.12               h03d6c58_0    defaults
lightgbm                  3.2.1            py37h295c915_0    defaults
llvmlite                  0.37.0           py37h295c915_1    defaults
lunarcalendar             0.0.9                      py_0    conda-forge
lz4-c                     1.9.3                h295c915_1    defaults
mako                      1.1.4              pyhd3eb1b0_0    defaults
markupsafe                2.0.1            py37h27cfd23_0    defaults
matplotlib                3.4.3            py37h06a4308_0    defaults
matplotlib-base           3.4.3            py37hbbc1b5f_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4           py37h14c3975_1001    defaults
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py37h7f8727e_0    defaults
mkl_fft                   1.3.1            py37hd3c417c_0    defaults
mkl_random                1.2.2            py37h51133e4_0    defaults
more-itertools            8.10.0             pyhd3eb1b0_0    defaults
msrest                    0.6.21             pyhd3eb1b0_0    defaults
multidict                 5.1.0            py37h27cfd23_2    defaults
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3                    py37_0    conda-forge
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py37h06a4308_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.3                  h7f8727e_0    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
netcdf4                   1.5.7            py37h0a24e14_0    defaults
networkx                  2.6.3              pyhd3eb1b0_0    defaults
notebook                  6.4.0            py37h06a4308_0    defaults
numba                     0.54.1           py37h51133e4_0    defaults
numexpr                   2.7.3            py37h22e1b3c_1    defaults
numpy                     1.20.3           py37hf144106_0    defaults
numpy-base                1.20.3           py37h74d4b33_0    defaults
oauthlib                  3.1.1              pyhd3eb1b0_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.6.4                      py_0    conda-forge
openssl                   1.1.1l               h7f8727e_0    defaults
optuna                    2.10.0             pyhd8ed1ab_0    conda-forge
orc                       1.6.7                h973521d_2    defaults
oscrypto                  1.2.1              pyhd3eb1b0_0    defaults
packaging                 21.0               pyhd3eb1b0_0    defaults
pandas                    1.3.4            py37h8c16a72_0    defaults
pandocfilters             1.4.3            py37h06a4308_1    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2            py37h06a4308_0    defaults
pbr                       5.6.0              pyhd3eb1b0_0    defaults
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.4.0            py37h5aabda8_0    defaults
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py37h06a4308_0    defaults
prettytable               2.4.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
prophet                   1.0.1            py37h89c1867_4    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pulp                      1.6.8                 py37_1000    conda-forge
py                        1.10.0             pyhd3eb1b0_0    defaults
py-xgboost                1.5.0            py37h89c1867_0    conda-forge
pyarrow                   4.0.1            py37he0739d4_3    defaults
pycausalimpact            0.1.1                    pypi_0    pypi
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.20                       py_2    defaults
pycryptodomex             3.10.1           py37h27cfd23_1    defaults
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyjwt                     2.1.0            py37h06a4308_0    defaults
pymc3                     3.11.4           py37hb070fc8_0    defaults
pymeeus                   0.5.11             pyhd3eb1b0_1    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.17.3           py37h7b6447c_0    defaults
pysocks                   1.7.1                    py37_1    defaults
pystan                    2.19.1.1         py37ha9443f7_0    defaults
pytest                    6.2.4            py37h06a4308_2    defaults
python                    3.7.3                h0371630_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-editor             1.0.4              pyhd3eb1b0_0    defaults
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pyyaml                    6.0              py37h7f8727e_1    defaults
pyzmq                     22.2.1           py37h295c915_1    defaults
qt                        5.9.7                h5867ecd_1    defaults
re2                       2020.11.01           h2531618_1    defaults
readline                  7.0                  h7b6447c_5    defaults
regex                     2021.8.3         py37h7f8727e_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
s3fs                      0.6.0              pyhd3eb1b0_0    defaults
s3transfer                0.4.2              pyhd3eb1b0_0    defaults
scikit-learn              1.0.1            py37h51133e4_0    defaults
scipy                     1.7.1            py37h292c36d_2    defaults
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
semver                    2.13.0             pyhd3eb1b0_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                58.0.4           py37h06a4308_0    defaults
setuptools-git            1.2              py37h28b3542_1    defaults
shap                      0.40.0           py37he8f5f7f_0    conda-forge
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
slicer                    0.0.7              pyhd3eb1b0_0    defaults
snappy                    1.1.8                he6710b0_0    defaults
snowflake-connector-python 2.6.2            py37h51133e4_0    defaults
snowflake-sqlalchemy      1.2.4              pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.23           py37h27cfd23_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
statsmodels               0.13.0           py37hb1e94ed_0    conda-forge
stevedore                 3.5.0            py37h89c1867_1    conda-forge
tbb                       2021.4.0             hd09550d_0    defaults
terminado                 0.9.4            py37h06a4308_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
theano-pymc               1.1.2            py37h51133e4_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py37h27cfd23_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.0              pyhd3eb1b0_0    defaults
typed-ast                 1.4.3            py37h7f8727e_1    defaults
typing-extensions         3.10.0.2             hd3eb1b0_0    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
tzlocal                   2.1                      py37_0    defaults
ujson                     4.0.2            py37h2531618_0    defaults
uriparser                 0.9.3                he6710b0_1    defaults
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
utf8proc                  2.6.1                h27cfd23_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.12.1           py37h7b6447c_1    defaults
xarray                    0.19.0             pyhd3eb1b0_1    defaults
xgboost                   1.5.0            py37h89c1867_0    conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yarl                      1.6.3            py37h27cfd23_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults
```

</details>

**Comment by skupr-anaconda** [comment]
Alembic 1.7.5 is available on defaults:

[main/noarch ](https://repo.anaconda.com/pkgs/main/noarch)
alembic-1.7.5-pyhd3eb1b0_0.tar.bz2

 And it should fix the issue. Verified by running:

`conda create -n alembic-test -y alembic=1.7.5`

`python -c "import alembic"`

**Comment by tvoipio** [comment]
The following works:

```python
conda create -n alembic-test -y alembic=1.7.5
conda activate alembic-test
python -c "import alembic"
```

However, the following does not - note the Python version:

```python
conda create -n alembic-test -y alembic=1.7.5 python=3.7.3
conda activate alembic-test
python -c "import alembic"
```

results in

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/runtime/environment.py", line 12, in <module>
    from .migration import MigrationContext
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/runtime/migration.py", line 27, in <module>
    from .. import ddl
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/ddl/mssql.py", line 14, in <module>
    from .base import AddColumn
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/ddl/base.py", line 14, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/util/__init__.py", line 1, in <module>
    from .editor import open_in_editor
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/util/editor.py", line 11, in <module>
    from .compat import is_posix
  File "/home/analytics_user/anaconda3/envs/alembic-test/lib/python3.7/site-packages/alembic/util/compat.py", line 33, in <module>
    import importlib_resources  # type:ignore[no-redef] # noqa
ModuleNotFoundError: No module named 'importlib_resources'
```

The metadata file `~/anaconda3/envs/alembic-test/conda-meta/alembic-1.7.5-pyhd3eb1b0_0.json` begins with

```json
{
  "build": "pyhd3eb1b0_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/noarch",
  "constrains": [],
  "depends": [
    "mako",
    "python >=3.6",
    "python-dateutil",
    "sqlalchemy >=1.3.0"
  ],
  "extracted_package_dir": "/home/analytics_user/anaconda3/pkgs/alembic-1.7.5-pyhd3eb1b0_0",
  "features": "",
  "files": [
    "lib/python3.7/site-packages/alembic-1.7.5.dist-info/INSTALLER",
```

Please note that `importlib_metadata` and `importlib_resources` are still missing from the `depends` block. The reason why this does not matter with Python 3.9 is that Python 3.9 already includes this functionality in standard library, while <3.9 do not. Please see https://github.com/sqlalchemy/alembic/blob/rel_1_7_4/setup.cfg#L42 .

The following _does_ work:

```python
conda create -n alembic-test -y alembic=1.7.5 python=3.7.3 importlib_metadata importlib_resources
conda activate alembic-test
python -c "import alembic"
```

which is the exact same workaround I have been using so far, but which is also the deviation between expected and actual behavior.

**Comment by tvoipio** [comment]
@skupr-anaconda Any update on this?

**Comment by skupr-anaconda** [comment]
There were removed preprocess-selectors that blocked using dependencies.
Alembic 1.7.5 was fixed (and bumped build number to **1**)
https://repo.anaconda.com/pkgs/main/noarch/ 

alembic-1.7.5-pyhd3eb1b0_1.tar.bz2

Also it was tested in the c3i_test2 channel:

```
conda create -n test_alembic_1.7.5 c3i_test2::alembic=1.7.5 python=3.7.3 -y

conda activate test_alembic_1.7.5

python -c "import alembic"
```

No issues.

```
conda create -n test_alembic_1.7.5 c3i_test2::alembic=1.7.5 python=3.8 -y

conda activate test_alembic_1.7.5

python -c "import alembic"
```

No issues.

**Comment by tvoipio** [comment]
Thanks for the fix, now it seems to work for my setup too!
