### ISSUE TITLE
Installing on M1 Mac fails because conda.exe is x86 executable

### ISSUE THREAD

**Issue by alexvoss** [ContinuumIO/anaconda-issues#12941]
### Actual Behavior

Installing [Miniconda3 macOS Apple M1 64-bit bash](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh) on an M1 Mac, I get the error message:

```
Miniconda3-latest-MacOSX-arm64.sh: line 410: /Users/<user>/miniconda3/conda.exe: Bad CPU type in executable
```

and, sure enough, `file conda.exe`gives me `conda.exe: Mach-O 64-bit executable x86_64`. I do not have Rosetta installed and think I should not need it.

### Expected Behavior

Installation should have succeeded. 

### Steps to Reproduce

Download [Miniconda3 macOS Apple M1 64-bit bash](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh) on a fresh MacOS install on an M1 Mac (such as a VM) and attempt installation.

##### Anaconda or Miniconda version:

According to the website, "latest" currently Conda 4.12.0 Python 3.9.7 released February 15, 2022.

##### Operating System:

MacOS 12.3.1

##### `conda info`
unable to provide as install fails

##### `conda list --show-channel-urls`
unable to provide as install fails

**Comment by pseudoyim** [comment]
Hi @alexvoss - thank you for bringing this to our attention. We confirmed the problem you reported and rebuilt the M1 Miniconda-4.12.0 installers. They are now available for download here: https://docs.conda.io/en/latest/miniconda.html

Please let us know if your issue is now resolved. Thank you.

**Comment by geoom** [comment]
this bug still persists on https://docs.conda.io/projects/miniconda/en/latest/ :(

**Comment by nelsonruth11** [comment]
Bug still persists

**Comment by marcoesters** [comment]
Hi @nelsonruth11, thanks for reporting that the bug still persists! I unfortunately cannot reproduce it.

In order to assist you, could you provide the following information?

* The link to the installer you used.
* The output of `sw_vers` in the terminal.
* The output of `uname -mr` in the terminal.

Thanks!
