### ISSUE TITLE
TkAgg backend broken in Python3 on Windows. _tkinter.TclError 

### ISSUE THREAD

**Issue by skjaeve** [ContinuumIO/anaconda-issues#211]
Opening interactive Matplotlib windows doesn't work with Python 3 and TkAgg backend. i get a _TclError traceback.
Same error in plain python interpreter. It works in python2.

```
[py3] C:\Users\Åsmund\Stuff>ipython
Python 3.4.2 |Continuum Analytics, Inc.| (default, Oct 22 2014, 11:51:45) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.use('tkagg')

In [3]: import matplotlib.pyplot as p

In [4]: p.ion()

In [5]: p.figure()
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\tkagg.py", line 17, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError: invalid command name "PyAggImagePhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Anaconda\envs\py3\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 278, in resize
    self.show()
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 350, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\tkagg.py", line 24, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError
Out[5]: <matplotlib.figure.Figure at 0x66aed68>

In [6]: Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\tkagg.py", line 17, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Anaconda\envs\py3\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "c:\Anaconda\envs\py3\lib\tkinter\__init__.py", line 582, in callit
    func(*args)
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 365, in idle_draw
    self.draw()
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 350, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "c:\Anaconda\envs\py3\lib\site-packages\matplotlib\backends\tkagg.py", line 24, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
In [6]:
```

**Comment by chanansh** [comment]
same problem as @skjaeve.
I am trying to plot when in debug console and I get errors all the time. Damm.
What is the solution?

**Comment by J-Sorenson** [comment]
Running Windows 8 64-bit on AMD with Anaconda Python 3.4 installed.  Qt interface works, but TkAgg backend fails with the same error.  Makes it a bit difficult to make my apps more cross-platform.  Is this being looked at yet, or should I install WxPython for now?

**Comment by mycr0ft** [comment]
Same issue with anaconda for Python 3.4 a year after the original post. I was settling on tkinter for students to learn since it is in default anaconda install as is matplotlib. Not working means I will have to switch to Qt/pyside next.

**Comment by CynthiaStar** [comment]
Confirmed 30th Nov 2015.
Anaconda Python 3.4, Windows 7 64bit, matplotlib back-end error.

Runnning:     
f = Figure(figsize=(5,5), dpi=100)
canvas = FigureCanvasTkAgg(f,self)
canvas.show()

  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\tkagg.py", line 24, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError

**Comment by ccordoba12** [comment]
Could you try with Python 3.5 and Matplotlib 1.5? I think Tk issues are fixed now in that combination :-)

**Comment by timskywalker** [comment]
Python 3.5 and Matplotlib 1.5.1 suffer the same problem, in Anaconda3-4.0.0

**Comment by naoko** [comment]
Encountering the same problem on Anaconda 4.0.7, python 3.5.1, matplotlib 1.5.1

**Comment by snimmagadda1** [comment]
Has there been any fix? Same issue Here

**Comment by pablo-esteban** [comment]
The problem persists on win7 64bit with:

- conda version : 4.1.11
- conda-env version : 2.5.2
- conda-build version : 1.14.1
- matplotlib: 1.5.1
- tk: 8.5.18

**Comment by christiaan20** [comment]
I am using tkagg.blitz to integrate a matplotlib plot into pysimplegui GUI, for me changing some of the tk variables to tk_image in envs\py3\lib\site-packages\matplotlib\backends\tkagg.py (see code below) fixed the error and showed the plot. my troubles with actually using plots in my application were not over but at least the example worked.

envs\py3\lib\site-packages\matplotlib\backends\tkagg.py :
``` 
def blit(photoimage, aggimage, bbox=None, colormode=1):
    tk_image = photoimage.tk

    if bbox is not None:
        bbox_array = bbox.__array__()
        # x1, x2, y1, y2
        bboxptr = (bbox_array[0, 0], bbox_array[1, 0],
                   bbox_array[0, 1], bbox_array[1, 1])
    else:
        bboxptr = 0
    data = np.asarray(aggimage)
    dataptr = (data.shape[0], data.shape[1], data.ctypes.data)
    try:
        tk_image.call(
            "PyAggImagePhoto", photoimage,
            dataptr, colormode, bboxptr)
    except tk.TclError:
        if hasattr(tk_image, 'interpaddr'):
            _tkagg.tkinit(tk_image.interpaddr(), 1)
        else:
            # very old python?
            _tkagg.tkinit(tk_image, 0)
        tk_image.call("PyAggImagePhoto", photoimage,
                dataptr, colormode, bboxptr)
```
