### ISSUE TITLE
Anaconda Navigator 1.6.2 GUI too big

### ISSUE THREAD

**Issue by MilaI3** [ContinuumIO/anaconda-issues#2983]
Hi,
I have just installed Anaconda Navigator 1.6.2 on Windows 10.
GUI display is too big and does not fit on my screen. I cannot access the top right icons or scroll down the display. 'Enable high DPI scaling' is activated. I tried to set 'QT_AUTO_SCREEN_SCALE_FACTOR=0.9
anaconda-navigator' in Anaconda prompt and I get a very small font after launching GUI, however it does not work on subsequent launches.
Could you please let me know how to resolve this issue?
Thanks.
Mila

![anaconda navigator display](https://user-images.githubusercontent.com/29758969/27991912-3d0c8bca-64b8-11e7-90f4-65bd2a961cd4.JPG)

**Comment by MilaI3** [comment]
The issue was resolved by deactivating 'Enable high DPI scaling' .

**Comment by planetmaker** [comment]
I don't think it's correct to close this bug.

Yes, the problem is solved when one de-activates high-DPI-scaling. However I don't think it is proper to throw at a new user a window which will cover several monitors. One may find this bug report and then know how to solve it - however a newly installed programme should not require a google search in order to fix-up the default GUI to something which resembles usable. It should be usable out-of-box.

**Comment by Nikhil-Garakapati** [comment]
@planetmaker How can we scale the size of Anaconda-Navigator GUI?

**Comment by netskink** [comment]
Indeed.  How do you change the scaling.  I'm at 1920x1080 and I can see 3/4 of the ui on linux

**Comment by netskink** [comment]
err cannot see

**Comment by atomsi** [comment]
find same issue on v1.87
![image](https://user-images.githubusercontent.com/4404196/44956550-3dfe5280-aef8-11e8-9988-2ec61be8e575.png)

**Comment by BenjiKCF** [comment]
the problem is back again and I cannot disable dpi  scaling because I couldn't press it

**Comment by Mauhing** [comment]
FIXED:  I think It is a bug. You have to TURN OFF the "enable high DPI scaling" to TURN ON the scaling.

It works well for me. My system is Ubuntu 18 and Anaconda Navigator 1.9.2.

**Comment by dogweather** [comment]
Yep - same issue on Fedora with a 1920x1080 screen.

1. Open App Preferences
2. Uncheck Hi-DPI scaling
3. Restart the app

**Comment by UbaidurRehman1** [comment]
> Yep - same issue on Fedora with a 1920x1080 screen.
> 
> 1. Open App Preferences
> 2. Uncheck Hi-DPI scaling
> 3. Restart the app

yeah, fixed

**Comment by electiondaze** [comment]
Ubuntu 18 LTS on Lenovo 6th gen Carbon with 1920x1080 screen. 
unchecking HDPI scaling and restarting app fixed the issue.

**Comment by NxNiki** [comment]
> Indeed. How do you change the scaling. I'm at 1920x1080 and I can see 3/4 of the ui on linux

I am using window 10 with a 4k display, and it just shows half of the UI. I cannot press the OK button so it stuck.

**Comment by saldisucipto** [comment]
> Ubuntu 18 LTS on Lenovo 6th gen Carbon with 1920x1080 screen.
> unchecking HDPI scaling and restarting app fixed the issue.

Thanks

**Comment by aarchiba** [comment]
Dell XPS 13 - default behaviour is the Navigator window hangs off the screen edges. Unchecking the scaling button results in a tiny window with text and icons too small to decipher. Neither option is usable.
![Screenshot from 2020-02-07 16-44-31](https://user-images.githubusercontent.com/136867/74047991-3edac400-49c9-11ea-8946-5627247f5768.png)

**Comment by adam3141** [comment]
> The issue was resolved by deactivating 'Enable high DPI scaling' .

I am using anaconda-navigator version 1.9.12

My screen size is 1360x768 - I was lucky to be able to just see the a few pixels of the checkbox for it so I could uncheck it. This needs to be fixed properly as I was unable to even scroll the dialog box (not sure if this is a problem with the underlying framework)

Maybe, it should be unchecked by default. Better for it to start too small than too big wouldn't you say?

**Comment by saharssm** [comment]
I had the same problem. I couldn't even move or resize the frame. Thanks for the solution. 
Problem solved!
Open App Preferences
Uncheck Hi-DPI scaling
Restart the app
It worked.

**Comment by gargee-suresh** [comment]
> The issue was resolved by deactivating 'Enable high DPI scaling' .

how do you do that?

**Comment by madgoks** [comment]
> > The issue was resolved by deactivating 'Enable high DPI scaling' .
> 
> how do you do that?

Open the anaconda navigator, choose preferences under the file menu and uncheck the High DPI Scaling option..

Hope it helps

**Comment by RobertMouncer** [comment]
This was an issue for me as the preferences window was too big for me to apply changes or even find the dpi setting.

How I fixed it:
1. `    nano ~/.anaconda/navigator/anaconda-navigator.ini `
2. find `enable_high_dpi_scaling` and set to `False`

**Comment by argonzalez82** [comment]
> This was an issue for me as the preferences window was too big for me to apply changes or even find the dpi setting.
> 
> How I fixed it:
> 
> 1. `   nano ~/.anaconda/navigator/anaconda-navigator.ini`
> 2. find `enable_high_dpi_scaling` and set to `False`

Thanks this solution worked for me as well, I had the same issue I couldn't access the preferences
in the GUI.

**Comment by lostdatum** [comment]
> 
> 
> the problem is back again and I cannot disable dpi scaling because I couldn't press it

So annoying indeed !
I had to go to C:\Users\username\AppData\Roaming\.anaconda\navigator\.anaconda\navigator and manually set enable_high_dpi_scaling to False.

**Comment by west474** [comment]
Same issue: Lenovo Ideapad Flex 5 AMD 4070U (screenshot below). 
Scaled using the DPI option then tabbing down from the bottom option 5 times to apply (taskbar is semi-opaque so could see the green go darker). 
Now screen is really small but better than really big I guess. Still happening in August 2021, figured I'd put a note for others looking for information on the same problem.

![image](https://user-images.githubusercontent.com/78795764/128382358-5476a562-b594-434c-aa63-ff831cd2c7b3.png)

**Comment by paketb0te** [comment]
Experienced the same issue on Ubuntu 20, unchecking the high-DPI scaling fixed it.

**Comment by jrendon** [comment]
So either we get "Super Big" or "Super Tiny" - wish there was a medium setting. Maybe next update?

**Comment by ramHruday** [comment]
Agree with @jrendon , it becomes either too bug or super tiny...
on Dell xps 13, #

**Comment by ArielMAJ** [comment]
Same here. 1920x1080 screen. If HiDPI is check i get a too big screen, if unchecked i get a too small screen. I already was forced to install anaconda (i really didn't wanted and tried to walk around it) so i could have things working without having a breakdown. Then on the first time I opened it I already had to face this... i wonder what more problems I'll run into just to set-up my final environment....

**Comment by Patrik-SE** [comment]
![Bildschirmfoto vom 2022-03-11 18-16-18](https://user-images.githubusercontent.com/35593938/157921202-4fb3bc21-8a16-4a0b-acaf-38e68d54a287.png)

Where can I uncheck anything?

**Comment by Shimin233** [comment]
Same for ASUS zenbook Duo, with Anaconda 2.2.0: either enabling DPI rescaling to get a super large one, or disabling it to get a tiny one. Does anyone find any updated solution in this version?

**Comment by akifcankilic** [comment]
> Same for ASUS zenbook Duo, with Anaconda 2.2.0: either enabling DPI rescaling to get a super large one, or disabling it to get a tiny one. Does anyone find any updated solution in this version?

Same problem for me with 2.2.0, too. My resolution is 1920 * 1080, prefer using tiny as I can see package names.

**Comment by Saadiq-Byte** [comment]
Same Problem, although I follow through with the process listed here, but am still having the same issue, HP EliteBook 840 G3

**Comment by Saadiq-Byte** [comment]
Problem solved, for now, I hope it doesn't come back knocking... lol
I uncheck and restart many times before solving

**Comment by ProgrammingCurve** [comment]
> The issue was resolved by deactivating 'Enable high DPI scaling' .

Open Anaconda Navigator and Execute 
>>QT_SCALE_FACTOR=0.8

Restart the application

**Comment by Saurav6789** [comment]
Navigate to anaconda prompt and type the following commands. It will work 

>set QT_SCALE_FACTOR=0.8( This number you can adjust according to your wish)
>anaconda-navigator

**Comment by AhmedElsiddieg** [comment]
On Mac OS, (will work on windows or ubuntu too probably)
Either run ``QT_SCALE_FACTOR=0.5 anaconda-navigator`` from terminal or in anaconda GUI open settings, configure Navigator and add the line ``QT_SCALE_FACTOR=0.5`` 
This worked for me on Mac OS, found it here: https://askubuntu.com/questions/1252036/zoom-and-anaconda-navigator-have-weird-scaling

**Comment by shivam9608** [comment]
This should NOT be marked closed. The issue persists. Even to disable the dpi scaling, we need some "apply" or "save" button which is visible only after changing the screen-resolution. Kindly reopen the issue, so that we can help fix this issue.

**Comment by tazenda31** [comment]
For Windows 11 Home, Anaconda Navigator v. 2.6.1., there seems to be at least one more way to fix it - in C:\Users\username\anaconda3\Scripts, find anaconda-navigator app and click on it. A dialog box should open. In it, click on the Properties button, and then Compatibility - there you can choose what you need.

**Comment by SoulNikhar** [comment]
Same issue: Hp pavilion AMD Ryzen 5 5500U  (screenshot below).
I am unable to uncheck the "Enable high-DPI scaling" option in the preferences.

**Comment by SoulNikhar** [comment]
Same issue: Hp pavilion AMD Ryzen 5 5500U (screenshot below).
I am unable to uncheck the "Enable high-DPI scaling" option in the preferences.

![Screenshot 2024-08-15 191143](https://github.com/user-attachments/assets/f2fa45ba-3833-4441-98f3-4bd2c08c7882)
