### ISSUE TITLE
UnxUtils patch needs admin privs

### ISSUE THREAD

**Issue by pelson** [ContinuumIO/anaconda-issues#424]
Need a patch utility for packaging py3 recipes, but "patch" is py2 only (see https://github.com/conda/conda-build/issues/498). UnxUtils provides a patch exe, but unfortunately, patch is the only exe in there that requires admin privileges. Is that a thing that can be changed in the UnxUtils recipe?

Thanks,

**Comment by ccordoba12** [comment]
I'm interested on fixing this. Is UnxUtils part of our official channels? Or is it in conda-recipes?

**Comment by pelson** [comment]
Looks like I'm the only person that has ever downloaded it: http://anaconda.org/anaconda/unxutils

**Comment by mwcraig** [comment]
FWIW, I was able to use the patch installed by default on appveyor (seems to be from git) once I edited the file names in the patch to remove the leading `a` and `b` added by git. `conda build` always runs patch with `-p0`...allowing that to be set to, e.g. `-p1`, would fix the issue (well on appveyor, anyway).

**Comment by msarahan** [comment]
Two things seem to be necessary here, assuming patch.exe is coming from Gnuwin32.

1. Embed a manifest to patch.exe that specifies that it does not need admin rights.
https://msdn.microsoft.com/en-us/library/bb756929.aspx
2. It was necessary for me to add the --binary flag to calls to patch.exe, because line endings are more of an issue on Windows.  YMMV.

Unless someone else jumps on this, I will be fixing this in the next couple of days by:

1. Replacing the conda patch package with this fixed exe
2. Removing the patch exe from unxutils
3. Making unxutils depend on the new patch package.

The patch program from git (applied from git) is nicer because it handles line endings through git, but we don't want to add a git dependency.

**Comment by ccordoba12** [comment]
Thanks @msarahan, I really appreciate it :-)

Another reason we can't depend on git: git needs bash to run. That's why it comes with GitBash on Windows.

**Comment by mwcraig** [comment]
:tada: @msarahan!

**Comment by msarahan** [comment]
More than a couple of days (sorry), but this should now be fixed.  Update your patch package (should be v 2.5 now, and is independent of Python version)

Note: conda-build will, at next release, depend on the patch package.  You won't need unxutils for this anymore (but you're welcome to use it for whatever else you need.)

cc @ilanschnell

**Comment by ccordoba12** [comment]
Great work @msarahan! This was really necessary since a long time ago :-)

**Comment by ccordoba12** [comment]
Closing as it's fixed now.

**Comment by pelson** [comment]
Excellent work guys. :+1:

**Comment by mortbauer** [comment]
Sorry guys, but for me this doesn't seem to work, I'm running conda 3.18.3 with a patch 2.5.9 on win-64 and it crashes with "The requested operation requires elevation". I figured out that the included patch.exe.manifest is not even extracted into the scripts folder, so I extracted it manually, however it still won't run. However after reading http://stackoverflow.com/a/17693764 i managed to fool windows by just renaming patch.exe, it ran if i called it mytest.exe.
