### ISSUE TITLE
CXXABI_1.3.9 not included in libstdc++.so.6

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#5191]
It seems to me that it's not possible to use some dynamically linked libraries (in my case /usr/lib/x86_64-linux-gnu/libmodplug.so.1) on ubuntu 17.04 because the libstdc++.so.6 shipped with conda does not include the CXXABI_1.3.9 symbols.

**Comment by mingwandroid** [comment]
Yes, that is the case. We are hoping to get in front of everything here, but it must be understood that this is a race and inevitably there'll be times when a distro is infront of us and things will break for people trying to do this kind of interoperation.

**Comment by tkelman** [comment]
Could try renaming (and patchelf-ing everything that links to it) the libstdc++ that was used to build conda packages, so at least the dynamic loader has a chance to also try loading the newer system copy? I believe that was the approach recommended by the manylinux wheel-builder folks from what they've learned.

**Comment by shaform** [comment]
Some of the libraries installed by conda (e.g., snappy) also requires CXXABI_1.3.9
```
$HOME/anaconda3/envs/tf/lib/libsnappy.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

**Comment by mingwandroid** [comment]
We have released `Anaconda Distribution 5` now which is built against `libstdc++` from `GCC 7.2.0` and therefore supports `CXXABI_1.3.9` (up to and including `CXXABI_1.3.11`) so you've run into the opposite problem; your system `libstdc++` doesn't support ``CXXABI_1.3.9` and you are trying to use that with `Anaconda Distribution 5` software.

I am assuming you have set `LD_LIBRARY_PATH` or `LD_PRELOAD` here? If not can you give details of your OS and exact reproduction steps please.

**Comment by shaform** [comment]
The environment is Ubuntu 16.04 x64

I was trying to compile caffe completely from Anaconda, so I did something like this:
```bash
conda create -n tf anaconda python=3.6
source activate tf
conda install atlas boost gflags glog hdf5 leveldb lmdb openblas protobuf
conda install -c menpo opencv3
git clone https://github.com/BVLC/caffe
cd caffe
cp Makefile.config.example Makefile.config
```
and set the compiler to link against `$(ANACONDA_HOME)/lib` by
```diff
5c5
< # USE_CUDNN := 1
---
> USE_CUDNN := 1
21c21
< # OPENCV_VERSION := 3
---
> OPENCV_VERSION := 3
68,69c68,69
< PYTHON_INCLUDE := /usr/include/python2.7 \
<       /usr/lib/python2.7/dist-packages/numpy/core/include
---
> # PYTHON_INCLUDE := /usr/include/python2.7 \
> #         /usr/lib/python2.7/dist-packages/numpy/core/include
72,75c72,75
< # ANACONDA_HOME := $(HOME)/anaconda
< # PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
<       # $(ANACONDA_HOME)/include/python2.7 \
<       # $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include
---
> ANACONDA_HOME := $(HOME)/anaconda3/envs/tf
> PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
>       $(ANACONDA_HOME)/include/python3.6 \
>       $(ANACONDA_HOME)/lib/python3.6/site-packages/numpy/core/include
83,84c83,84
< PYTHON_LIB := /usr/lib
< # PYTHON_LIB := $(ANACONDA_HOME)/lib
---
> # PYTHON_LIB := /usr/lib
> PYTHON_LIB := $(ANACONDA_HOME)/lib
```

However, doing so would cause the following error:

> undefined reference to `google::protobuf::internal::WireFormatLite

I suspect that this is because Ubuntu 16.04 has gcc 5.x, because I was able to compile in this way under Ubuntu 14.04 in the past.

Therefore, I decided to install gcc in Anaconda by
```bash
conda install gcc libgcc
```

and change the compiler to 
```diff
25c25
< # CUSTOM_CXX := g++
---
> CUSTOM_CXX := $(HOME)/anaconda3/envs/tf/bin/g++
 ```
and eventually the error was produced:
> $HOME/anaconda3/envs/tf/lib/libsnappy.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

**Comment by mingwandroid** [comment]
The `gcc` and `libgcc` packages are deprecated now. Please try `gxx_linux-64` instead. Note these compilers have prefixed names.

**Comment by shaform** [comment]
@mingwandroid Thanks, but CUDA only supports GCC <= 5.x[1] and even if I turn off CUDA I still encounter the following issue:

> $HOME/anaconda3/envs/tf/lib/libopencv_highgui.so: undefined reference to `gtk_widget_get_type'

I really don't know why but I found that I am able to compile if I set:

```diff
25c25
< # CUSTOM_CXX := g++
---
> CUSTOM_CXX := /usr/bin/g++-4.9
```

[1]: I know Anaconda has a package called [cudatoolkit](https://anaconda.org/anaconda/cudatoolkit), but it doesn't seem to include the header files.

**Comment by 8greg8** [comment]
There is an issue in anaconda where libstdc++ is not linking to version 6.0.24 but rather to 6.0.19. If you manually relink libstdc++.so and libstdc++.so.6 to libstdc++.so.6.0.24 it should work.

**Comment by bearpaw** [comment]
@8greg8 Thanks a lot! You save my life!

**Comment by kvas7andy** [comment]
@8greg8 worked, thnx. Put /home/user/anaconda2/lib/libstdc++.so.6.0.24 in LD_PRELOAD enviroment variable.
Doesn't anyone know if anaconda pkgs will be updated, will this olution still work?
Will that problem be fixed in new update?

**Comment by masonkirchner** [comment]
@8greg8 Could you elaborate on what you mean by manually relinking libstdc++.so and libstdc++.so.6 to libstdc++.so.6.0.24

**Comment by Inoho** [comment]
@8greg8 I have a same query as @masonkirchner , Could you please explain how to relink libstdc++.so and libstdc++.so.6 to libstdc++.so.6.0.24.

**Comment by kmyokoyama** [comment]
Maybe I can help explaining how to relink. This is the way I did it:

1. Confirm that there is an `libstdc++.so.6.0.24` in ~/anaconda3/lib/:
`$ ls libstdc++.so.6.0.24`
2. Confirm that there is a __symlink__ `libstdc++.so.6` in ~/anaconda3/lib/:
`$ ls libstdc++.so.6`
3. Remove the existing symlink (in my case `libstdc++.so.6 -> libstdc++.so.6.0.19`):
`$ rm ~/anaconda3/lib/libstdc++.so.6`
4. Relink it to `libstdc++.so.6.0.24`:
`$ ln -s libstdc++.so.6.0.24 libstdc++.so.6`

It worked for me.

**Comment by ahinsutime** [comment]
kmyokoyama, it worked! Thanks!

**Comment by subinoy** [comment]
In our system there are links with libstdc++.so and libstdc++.so.6  to libstdc++.so.6.0.19. But there is no libstdc++.so.6.0.24
How can I get that lib and our system is also complaining abt the 
OSError: /opt/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/anaconda3/lib/python3.6/site-packages/porechop/cpp_functions.so)

So, I need help. How can I solve the issue.
Thanks!

**Comment by mingwandroid** [comment]
You just need to make sure you are not using either of the old `gcc` nor the `libgcc` packages.

**Comment by htso** [comment]
Can you elaborate on how to find out if I'm using old libgcc packages. My gcc is version 4.8.4

**Comment by mingwandroid** [comment]
> Can you elaborate on how to find out if I'm using old libgcc packages.

`conda list --show-channel-urls` will show you what packages you have installed.

> My gcc is version 4.8.4

Your system GCC does not matter here. Conda environments are (almost fully) self-contained.

**Comment by mingwandroid** [comment]
Run `conda list --show-channel-urls`

**Comment by mingwandroid** [comment]
conda remove libgcc

**Comment by mingwandroid** [comment]
Then conda install libgcc-ng --force

It does not matter that the list is long, please paste the whole thing.

**Comment by willigott** [comment]
I do have the same issue when I try to import [tellurium](http://tellurium.analogmachine.org/) which I installed using
 `pip install git+https://github.com/sys-bio/tellurium.git`

When I then try

`import tellurium as te`

I get

> ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by path/to/anaconda2/lib/python2.7/site-packages/matplotlib/_path.so)

When I first do `import matplotlib.pyplot as plt`, the import works fine.

I checked

`ls -l ~/anaconda2/lib/libstdc++.so.6`

which returns

`path/to/anaconda2/lib/libstdc++.so.6 -> libstdc++.so.6.0.24`

so the linking should be ok.

`conda list --show-channel-urls`

returns

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0    defaults
alabaster                 0.7.10           py27he5a193a_0    defaults
anaconda                  5.1.0                    py27_2    defaults
anaconda-client           1.6.9                    py27_0    defaults
anaconda-navigator        1.7.0                    py27_0    defaults
anaconda-project          0.8.2            py27h236b58a_0    defaults
antimony                  2.9.4                     <pip>
appdirs                   1.4.3                     <pip>
asn1crypto                0.24.0                   py27_0    defaults
astroid                   1.6.1                    py27_0    defaults
astropy                   2.0.3            py27h14c3975_0    defaults
attrs                     17.4.0                   py27_0    defaults
babel                     2.5.3                    py27_0    defaults
backports                 1.0              py27h63c9359_1    defaults
backports.functools_lru_cache 1.4              py27he8db605_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2    defaults
backports_abc             0.5              py27h7b3c97b_0    defaults
beautifulsoup4            4.6.0            py27h3f86ba9_1    defaults
bitarray                  0.8.1            py27h14c3975_1    defaults
bkcharts                  0.2              py27h241ae91_0    defaults
blaze                     0.11.3           py27h5f341da_0    defaults
bleach                    2.1.2                    py27_0    defaults
bokeh                     0.12.13          py27h5233db4_0    defaults
boto                      2.48.0           py27h9556ac2_1    defaults
bottleneck                1.2.1            py27h21b16a3_0    defaults
bzip2                     1.0.6                h9a117a8_4    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
cairo                     1.14.12              h77bcde2_0    defaults
cdecimal                  2.3              py27h14c3975_3    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.4           py27h9745a5d_0    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
click                     6.7              py27h4225b90_0    defaults
cloudpickle               0.5.2                    py27_1    defaults
clyent                    1.2.2            py27h7276e6c_1    defaults
cobra                     0.11.3                    <pip>
colorama                  0.3.9            py27h5cde069_0    defaults
conda                     4.4.10                   py27_0    defaults
conda-build               3.4.1                    py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py27hf052a9d_0    defaults
configparser              3.5.0            py27h5117587_0    defaults
contextlib2               0.5.5            py27hbf4c468_0    defaults
cryptography              2.1.4            py27h6697b16_0    defaults
curl                      7.58.0               h84994c4_0    defaults
cycler                    0.10.0           py27hc7354d3_0    defaults
cython                    0.27.3           py27hc56b35e_0    defaults
cytoolz                   0.9.0            py27h14c3975_0    defaults
dask                      0.16.1                   py27_0    defaults
dask-core                 0.16.1                   py27_0    defaults
datashape                 0.5.4            py27hf507385_0    defaults
dbus                      1.12.2               hc3f9b76_1    defaults
decorator                 4.2.1                    py27_0    defaults
distributed               1.20.2                   py27_0    defaults
docutils                  0.14             py27hae222c1_0    defaults
entrypoints               0.2.3            py27h502b47d_2    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
Escher                    1.6.0                     <pip>
et_xmlfile                1.0.1            py27h75840f5_0    defaults
expat                     2.2.5                he0dffb1_0    defaults
fastcache                 1.0.2            py27h14c3975_2    defaults
filelock                  2.0.13           py27h61a9c69_0    defaults
flask                     0.12.2           py27h6d5c1cd_0    defaults
flask-cors                3.0.3            py27h1a8a27f_0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  hab7d2ae_1    defaults
funcsigs                  1.0.2            py27h83f16ab_0    defaults
functools32               3.2.3.2          py27h4ead58f_1    defaults
future                    0.16.0                    <pip>
futures                   3.2.0            py27h7b459c0_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py27h475ea6a_0    defaults
glib                      2.53.6               h5d9569c_2    defaults
glob2                     0.6              py27hcea9cbd_0    defaults
glpk                      0.3                       <pip>
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py27h4cf3fa8_2    defaults
graphite2                 1.3.10               hf63cedd_1    defaults
greenlet                  0.4.12           py27hac09c53_0    defaults
grin                      1.2.1                    py27_4    defaults
gst-plugins-base          1.12.4               h33fb286_0    defaults
gstreamer                 1.12.4               hb53b477_0    defaults
h5py                      2.7.1            py27h2697762_0    defaults
harfbuzz                  1.7.4                hc5b324e_0    defaults
hdf5                      1.10.1               h9caa474_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1            py27h5233db4_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py27h5722d68_1    defaults
imageio                   2.2.0            py27hf108a7f_0    defaults
imagesize                 0.7.1            py27hd17bf80_0    defaults
intel-openmp              2018.0.0             hc7b2577_8    defaults
ipaddress                 1.0.19                   py27_0    defaults
ipykernel                 4.8.0                    py27_0    defaults
ipython                   5.4.1                    py27_2    defaults
ipython_genutils          0.2.0            py27h89fb69b_0    defaults
ipywidgets                7.1.1                    py27_0    defaults
isodate                   0.6.0                     <pip>
isort                     4.2.15           py27hcfa4749_0    defaults
itsdangerous              0.24             py27hb8295c1_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py27h2cc5433_0    defaults
jedi                      0.11.1                   py27_0    defaults
jinja2                    2.10             py27h4114e70_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                2.6.0            py27h7ed5aa4_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter_client            5.2.2                    py27_0    defaults
jupyter_console           5.2.0            py27hc6bee7e_1    defaults
jupyter_core              4.4.0            py27h345911c_0    defaults
jupyterlab                0.31.5                   py27_0    defaults
jupyterlab_launcher       0.10.2                   py27_0    defaults
lazy-object-proxy         1.3.1            py27h682c727_0    defaults
libcurl                   7.58.0               h1ad7b7a_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.34               hb9fc6fc_0    defaults
libroadrunner             1.4.24                    <pip>
libsodium                 1.0.15               hf101ebd_0    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                h28f6b97_0    defaults
libtool                   2.4.6                h544aabb_3    defaults
libxcb                    1.12                 hcd93eb1_4    defaults
libxml2                   2.9.7                h26e45fe_0    defaults
libxslt                   1.1.32               h1312cb7_0    defaults
llvmlite                  0.21.0           py27h6dad3f9_0    defaults
locket                    0.2.0            py27h73929a2_1    defaults
lxml                      4.1.1            py27hf71bdeb_1    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.0              py27h97b2822_1    defaults
matplotlib                2.1.2            py27h0e671d2_0    defaults
mccabe                    0.6.1            py27h0e7c7be_1    defaults
mistune                   0.8.3                    py27_0    defaults
mkl                       2018.0.1             h19d6760_4    defaults
mkl-service               1.1.2            py27hb2d42c5_4    defaults
mpc                       1.0.3                hec55b23_5    defaults
mpfr                      3.1.5                h11a74b3_2    defaults
mpmath                    1.0.0            py27h9669132_2    defaults
msgpack-python            0.5.1            py27h6bb024c_0    defaults
multipledispatch          0.4.9            py27h9b5f95a_0    defaults
navigator-updater         0.1.0            py27h0f9cd39_0    defaults
nbconvert                 5.3.1            py27he041f76_0    defaults
nbformat                  4.4.0            py27hed7f2b2_0    defaults
ncurses                   6.0                  h9df7e31_2    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.2.5            py27hec5f4de_0    defaults
nose                      1.3.7            py27heec2199_2    defaults
notebook                  5.4.0                    py27_0    defaults
numba                     0.36.2          np114py27he2868da_0    defaults
numexpr                   2.6.4            py27hd318778_0    defaults
numpy                     1.14.0           py27h3dfced4_1    defaults
numpydoc                  0.7.0            py27h9647a75_0    defaults
odo                       0.5.1            py27h9170de3_0    defaults
olefile                   0.45.1                   py27_0    defaults
openpyxl                  2.4.10                   py27_0    defaults
openssl                   1.0.2o               h20670df_0    defaults
optlang                   1.4.1                     <pip>
packaging                 16.8             py27h5e07c7c_1    defaults
pandas                    0.22.0           py27hf484d3e_0    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py27h428e1e5_1    defaults
pango                     1.41.0               hd475d92_0    defaults
parso                     0.1.1            py27h718acc2_0    defaults
partd                     0.3.8            py27h4e55004_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.5             py27hefe4bee_0    defaults
pathlib2                  2.3.0            py27h6e9d198_0    defaults
patsy                     0.5.0                    py27_0    defaults
pcre                      8.41                 hc27e229_1    defaults
pep8                      1.7.1                    py27_0    defaults
pexpect                   4.3.1                    py27_0    defaults
phrasedml                 1.0.9                     <pip>
pickleshare               0.7.4            py27h09770e1_0    defaults
pillow                    5.0.0            py27h3deb7b8_0    defaults
pip                       9.0.1            py27ha730c48_4    defaults
pixman                    0.34.0               hceecf20_3    defaults
pkginfo                   1.4.1            py27hee1a9ad_1    defaults
plotly                    2.5.1                     <pip>
pluggy                    0.6.0            py27h1f4f128_0    defaults
ply                       3.10             py27hd6d9ae5_0    defaults
prompt_toolkit            1.0.15           py27h1b593e1_0    defaults
psutil                    5.4.3            py27h14c3975_0    defaults
ptyprocess                0.5.2            py27h4ccb14c_0    defaults
py                        1.5.2            py27h203d672_0    defaults
pycairo                   1.15.4           py27h1b9232e_1    defaults
pycodestyle               2.3.1            py27h904819d_0    defaults
pycosat                   0.6.3            py27ha4109ae_0    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pycrypto                  2.6.1            py27h14c3975_7    defaults
pycurl                    7.43.0.1         py27hb7f436b_0    defaults
pyflakes                  1.6.0            py27h904a57d_0    defaults
pygments                  2.2.0            py27h4a8b6f5_0    defaults
pylint                    1.8.2                    py27_0    defaults
pyodbc                    4.0.22           py27hf484d3e_0    defaults
pyopenssl                 17.5.0           py27hcee3be0_0    defaults
pyparsing                 2.2.0            py27hf1513f8_1    defaults
pyqt                      5.6.0            py27h4b1e83c_5    defaults
pysocks                   1.6.7            py27he2db6d2_1    defaults
pytables                  3.4.2            py27h1f7bffc_2    defaults
pytest                    3.3.2                    py27_0    defaults
python                    2.7.14              h1571d57_29    defaults
python-dateutil           2.6.1            py27h4ca5741_1    defaults
python-libsbml            5.16.0           py27hded5652_0    sbmlteam
pytz                      2017.3           py27h001bace_0    defaults
pywavelets                0.5.2            py27hecda097_0    defaults
pyyaml                    3.12             py27h2d70dd7_1    defaults
pyzmq                     16.0.3           py27hc579512_0    defaults
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py27hd7914c3_0    defaults
qtconsole                 4.3.1            py27hc444b0d_0    defaults
qtpy                      1.3.1            py27h63d3751_0    defaults
rdflib                    4.2.2                     <pip>
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py27hc5b0589_1    defaults
rope                      0.10.7           py27hfe459b0_0    defaults
rrplugins                 1.1.10                    <pip>
ruamel.ordereddict        0.4.13                    <pip>
ruamel.yaml               0.14.12                   <pip>
ruamel_yaml               0.15.35          py27h14c3975_1    defaults
sbml2matlab               0.9.1                     <pip>
scandir                   1.6              py27hf7388dc_0    defaults
scikit-image              0.13.1           py27h14c3975_1    defaults
scikit-learn              0.19.1           py27h445a80a_0    defaults
scipy                     1.0.0            py27hf5f0f52_0    defaults
seaborn                   0.8.1            py27h633ea1e_0    defaults
send2trash                1.4.2                    py27_0    defaults
setuptools                38.4.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3          py27h9bcb476_0    defaults
sip                       4.18.1           py27he9ba0ab_2    defaults
six                       1.11.0           py27h5f960f1_1    defaults
snowballstemmer           1.2.1            py27h44e2768_0    defaults
sortedcollections         0.5.3            py27h135218e_0    defaults
sortedcontainers          1.5.9                    py27_0    defaults
SPARQLWrapper             1.8.1                     <pip>
sphinx                    1.6.6                    py27_0    defaults
sphinxcontrib             1.0              py27h1512b58_1    defaults
sphinxcontrib-websupport  1.0.1            py27hf906f22_1    defaults
spyder                    3.2.6                    py27_0    defaults
sqlalchemy                1.2.1            py27h14c3975_0    defaults
sqlite                    3.22.0               h1bed415_0    defaults
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2    defaults
statsmodels               0.8.0            py27hc87d62d_0    defaults
subprocess32              3.2.7            py27h373dbce_0    defaults
swiglpk                   1.4.4                     <pip>
sympy                     1.1.1            py27hc28188a_0    defaults
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py27h51fe5ba_0    defaults
tecombine                 0.2.2.1                   <pip>
tellurium                 2.0.12                    <pip>
tenuml                    1.1.1                     <pip>
terminado                 0.8.1                    py27_1    defaults
tesbml                    5.15.0.1                  <pip>
tesedml                   0.4.3                     <pip>
testpath                  0.3.1            py27hc38d2c4_0    defaults
tk                        8.6.7                hc745277_3    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   4.5.3                    py27_0    defaults
traitlets                 4.3.2            py27hd6ce930_0    defaults
typing                    3.6.2            py27h66f49e2_0    defaults
unicodecsv                0.14.1           py27h5062da9_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py27ha55213b_0    defaults
wcwidth                   0.1.7            py27h9e3e1ab_0    defaults
webencodings              0.5.1            py27hff10b21_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.30.0           py27h2bc6bb2_1    defaults
widgetsnbextension        3.1.0                    py27_0    defaults
wrapt                     1.10.11          py27h04f6869_0    defaults
xlrd                      1.1.0            py27ha77178f_1    defaults
xlsxwriter                1.0.2            py27h12cbc6b_0    defaults
xlwt                      1.3.0            py27h3d85d97_0    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.2                hbedb6e5_2    defaults
zict                      0.1.3            py27h12c336c_0    defaults
zlib                      1.2.11               ha838bed_2    defaults
```

Any idea how to fix this?

**Comment by rockyzhengwu** [comment]
I update LD_LIBARARY_PATH in .basrc
```
export LD_LIBRARY_PATH="/home/myname/anaconda3/lib:$LD_LIBRARY_PATH"
```

**Comment by htso** [comment]
This issue has not gone away. Here is my 

conda list --show-channel-urls

```
### # packages in environment at /home/rspace/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0    defaults
_nb_ext_conf              0.4.0                    py36_1    defaults
absl-py                   0.1.13                    <pip>
alabaster                 0.7.10           py36h306e16b_0    defaults
anaconda                  custom           py36hbbc8b67_0    defaults
anaconda-client           1.6.5            py36h19c0dcd_0    defaults
anaconda-navigator        1.6.9            py36h11ddaaa_0    defaults
anaconda-project          0.8.0            py36h29abdf5_0    defaults
arctic                    1.55.0                    <pip>
asn1crypto                0.22.0           py36h265ca7c_1    defaults
astor                     0.6.2                     <pip>
astroid                   1.5.3            py36hbdb9df2_0    defaults
astropy                   2.0.2            py36ha51211e_4    defaults
atari-py                  0.1.1                     <pip>
babel                     2.5.0            py36h7d14adf_0    defaults
backports                 1.0              py36hfa02d7e_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    defaults
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
bintrees                  2.0.7                     <pip>
bitarray                  0.8.1            py36h5834eb8_0    defaults
bkcharts                  0.2              py36h735825a_0    defaults
blaze                     0.11.3           py36h4e06776_0    defaults
bleach                    1.5.0                     <pip>
bleach                    2.0.0            py36h688b259_0    defaults
bokeh                     0.12.10          py36hbb0e44a_0    defaults
boto                      2.48.0           py36h6e4cd66_1    defaults
bottleneck                1.2.1            py36haac1ea0_0    defaults
Box2D-kengz               2.3.3                     <pip>
bzip2                     1.0.6                h0376d23_1    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.10              haa5651f_5    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.10.0           py36had8d393_1    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    defaults
cloudpickle               0.4.0            py36h30f8c20_0    defaults
clyent                    1.2.2            py36h7e57e65_1    defaults
colorama                  0.3.9            py36h489cec4_0    defaults
conda                     4.5.1                    py36_0    defaults
conda-build               3.0.27           py36h940a66d_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h98955d8_0    defaults
contextlib2               0.5.5            py36h6c84a62_0    defaults
cryptography              2.0.3            py36ha225213_1    defaults
curl                      7.55.1               hcb0b314_2    defaults
cycler                    0.10.0           py36h93f1223_0    defaults
cython                    0.26.1           py36h21c49d0_0    defaults
cytoolz                   0.8.2            py36h708bfd4_0    defaults
dask                      0.15.3           py36hdc2c8aa_0    defaults
dask                      0.17.2                    <pip>
dask-core                 0.15.3           py36h10e6167_0    defaults
datashape                 0.5.4            py36h3ad6b5c_0    defaults
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.1.2            py36hd076ac8_0    defaults
deepdish                  0.3.6                     <pip>
distributed               1.19.1           py36h25f3894_0    defaults
dnspython                 1.15.0                    <pip>
docutils                  0.14             py36hb0f60f5_0    defaults
ecdsa                     0.13                      <pip>
Electrum                  3.0.2                     <pip>
entrypoints               0.2.3            py36h1aec115_2    defaults
enum34                    1.1.6                     <pip>
et_xmlfile                1.0.1            py36hd6bccc3_0    defaults
expat                     2.2.4                hc00ebd1_1    defaults
fastcache                 1.0.2            py36h5b0c431_0    defaults
filelock                  2.0.12           py36hacfa1f5_0    defaults
flask                     0.12.2           py36hb24657c_0    defaults
flask-cors                3.0.3            py36h2d857d3_0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  h52ed37b_0    defaults
future                    0.16.0                    <pip>
gast                      0.2.0                     <pip>
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py36h2fe25dc_0    defaults
glib                      2.53.6               hc861d11_1    defaults
glob2                     0.5              py36h2c1b292_1    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gmpy2                     2.0.8            py36h55090d7_1    defaults
graphite2                 1.3.10               hc526e54_0    defaults
greenlet                  0.4.12           py36h2d503a6_0    defaults
grpcio                    1.10.1                    <pip>
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
gym                       0.9.3                     <pip>
h5py                      2.7.0            py36he81ebca_1    defaults
harfbuzz                  1.5.0                h2545bd6_0    defaults
hdbscan                   0.8.12                    <pip>
hdf5                      1.10.1               hb0523eb_0    defaults
heapdict                  1.0.0            py36h79797d7_0    defaults
html5lib                  0.999999999      py36h2cfc398_0    defaults
html5lib                  0.9999999                 <pip>
hypertools                0.5.0                     <pip>
icu                       58.2                 h211956c_0    defaults
idna                      2.6              py36h82fb2a8_1    defaults
imageio                   2.2.0            py36he555465_0    defaults
imagesize                 0.7.1            py36h52d8127_0    defaults
imgaug                    0.2.5                     <pip>
inflection                0.3.1                     <pip>
intel-openmp              2018.0.0             h15fc484_7    defaults
ipykernel                 4.6.1            py36hbf841aa_0    defaults
ipyparallel               6.1.1                     <pip>
ipython                   6.1.0            py36hc72a948_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.0.0            py36h7b55c3a_0    defaults
isort                     4.2.15           py36had401c0_0    defaults
itsdangerous              0.24             py36h93cc618_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py36h4c697fb_0    defaults
jedi                      0.10.2           py36h552def0_0    defaults
jinja2                    2.9.6            py36h489bce4_1    defaults
jpeg                      9b                   habf39ab_1    defaults
jsonrpclib-pelix          0.3.1                     <pip>
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0            py36h9896ce5_0    defaults
jupyter_client            5.1.0            py36h614e9ea_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.3.0            py36h357a921_0    defaults
jupyterlab                0.27.0           py36h86377d0_2    defaults
jupyterlab_launcher       0.4.0            py36h4d8058d_0    defaults
Keras                     2.1.5                     <pip>
lazy-object-proxy         1.3.1            py36h10fcdad_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc                    5.2.0                         0    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libssh2                   1.8.0                h8c220ad_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.8                h90200ff_9    defaults
libtool                   2.4.6                hd50d1a6_0    defaults
libxcb                    1.12                 h84ff03f_3    defaults
libxml2                   2.9.4                h6b072ca_5    defaults
libxslt                   1.1.29               hcf9102b_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36h787c0ad_1    defaults
lxml                      4.1.0            py36h5b66e50_0    defaults
lzo                       2.10                 h1bfc0ba_1    defaults
Markdown                  2.6.11                    <pip>
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                2.1.0            py36hba5de38_0    defaults
mccabe                    0.6.1            py36h5ad9710_1    defaults
mistune                   0.7.4            py36hbab8784_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
mkl-service               1.1.2            py36h17a0993_4    defaults
mockextras                1.0.2                     <pip>
more-itertools            4.0.1                     <pip>
mpc                       1.0.3                hf803216_4    defaults
mpfr                      3.1.5                h12ff648_1    defaults
mpmath                    0.19             py36h8cc018b_2    defaults
msgpack-python            0.4.8            py36hec4c5d1_0    defaults
mujoco-py                 0.5.7                     <pip>
multipledispatch          0.4.9            py36h41da3fb_0    defaults
navigator-updater         0.1.0            py36h14770f7_0    defaults
nb_anacondacloud          1.4.0                    py36_0    defaults
nb_conda                  2.2.1            py36h8118bb2_0    defaults
nb_conda_kernels          2.1.0                    py36_0    defaults
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
nbpresent                 3.0.2            py36h5f95a39_1    defaults
ncurses                   6.0                  h06874d7_1    defaults
ndg-httpsclient           0.4.3                     <pip>
networkx                  2.0              py36h7e96fb8_0    defaults
nltk                      3.2.4            py36h1a0979f_0    defaults
nose                      1.3.7            py36hcdf7029_2    defaults
notebook                  5.0.0            py36h0b20546_2    defaults
numba                     0.35.0             np113py36_10    defaults
numexpr                   2.6.2            py36hdd3393f_1    defaults
numpy                     1.14.2                    <pip>
numpy                     1.13.3           py36ha12f23b_0    defaults
numpydoc                  0.7.0            py36h18f165f_0    defaults
odo                       0.5.1            py36h90ed295_0    defaults
olefile                   0.44             py36h79f9f78_0    defaults
opencv-python             3.4.0.12                  <pip>
openpyxl                  2.4.8            py36h41dd2a8_1    defaults
openssl                   1.0.2o               h20670df_0    defaults
pachi-py                  0.0.21                    <pip>
packaging                 16.8             py36ha668100_1    defaults
pandas                    0.21.1           py36h20b78c2_0    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
pango                     1.40.11              h8191d47_0    defaults
partd                     0.3.8            py36h36fd896_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.3.1           py36he0c6f6d_0    defaults
pathlib2                  2.3.0            py36h49efa8e_0    defaults
patsy                     0.4.1            py36ha3be15e_0    defaults
pbkdf2                    1.3                       <pip>
pcre                      8.41                 hc71a17e_0    defaults
pep8                      1.7.0            py36h26ade29_0    defaults
pexpect                   4.2.1            py36h3b9d41b_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pillow                    4.2.1            py36h9119f52_0    defaults
pip                       9.0.1            py36h8ec8b28_3    defaults
pip                       9.0.3                     <pip>
pixman                    0.34.0               h83dc358_2    defaults
pkginfo                   1.4.1            py36h215d178_1    defaults
ply                       3.10             py36hed35086_0    defaults
ppca                      0.0.3                     <pip>
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
protobuf                  3.5.2.post1               <pip>
psutil                    5.4.0            py36h84c53db_0    defaults
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.4.34           py36h0712aa3_1    defaults
pyaes                     1.6.1                     <pip>
pyasn1                    0.4.2                     <pip>
pycocotools               2.0                       <pip>
pycodestyle               2.3.1            py36hf609f19_0    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pycrypto                  2.6.1            py36h6998063_1    defaults
pycurl                    7.43.0           py36h5e72054_3    defaults
pyflakes                  1.6.0            py36h7bd6a15_0    defaults
pygame                    1.9.3                     <pip>
pyglet                    1.2.4                     <pip>
pygments                  2.2.0            py36h0d3125c_0    defaults
pylint                    1.7.4            py36hb9d4533_0    defaults
pymongo                   3.6.0                     <pip>
pymongo                   3.5.1                     <pip>
pyodbc                    4.0.17           py36h999153c_0    defaults
PyOpenGL                  3.1.0                     <pip>
pyopenssl                 17.2.0           py36h5cc804b_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pyqt                      5.6.0            py36h0386399_5    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytables                  3.4.2            py36h3b5282a_2    defaults
pytest                    3.2.1            py36h11ad3bb_1    defaults
python                    3.6.5                hc3d631a_0    defaults
python-dateutil           2.6.1            py36h88d3b88_1    defaults
pytz                      2017.2           py36hc2ccc2a_1    defaults
pywavelets                0.5.2            py36he602eb0_0    defaults
pyyaml                    3.12             py36hafb9ca4_1    defaults
pyzmq                     16.0.2           py36h3b0cf96_2    defaults
qrcode                    5.3                       <pip>
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py36h609ed8c_0    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
qtpy                      1.3.1            py36h3691cc8_0    defaults
Quandl                    3.2.1                     <pip>
readline                  7.0                  hac23ff0_3    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
requests                  2.13.0                    <pip>
rope                      0.10.5           py36h1f8c17e_0    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
scikit-image              0.13.0           py36had3c07a_1    defaults
scikit-learn              0.19.1           py36h7aa7ec6_0    defaults
scipy                     1.0.1                     <pip>
scipy                     0.19.1           py36h9976243_3    defaults
seaborn                   0.8.1                     <pip>
seaborn                   0.8.0            py36h197244f_0    defaults
setuptools                39.0.1                    <pip>
setuptools                36.5.0           py36he42e2e1_0    defaults
simplegeneric             0.8.1            py36h2cb9092_0    defaults
singledispatch            3.4.0.3          py36h7a266c3_0    defaults
sip                       4.18.1           py36h51ed4ed_2    defaults
six                       1.11.0           py36h372c433_1    defaults
six                       1.11.0                    <pip>
snowballstemmer           1.2.1            py36h6febd40_0    defaults
sortedcollections         0.5.3            py36h3c761f9_0    defaults
sortedcontainers          1.5.7            py36hdf89491_0    defaults
sphinx                    1.6.3            py36he5f0bdb_0    defaults
sphinxcontrib             1.0              py36h6d0f590_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    defaults
spyder                    3.2.4            py36hbe6152b_0    defaults
sqlalchemy                1.1.13           py36hfb5efd7_0    defaults
sqlite                    3.22.0               h1bed415_0    defaults
statsmodels               0.8.0            py36h8533d0b_0    defaults
sympy                     1.1.1            py36hc6d1c1c_0    defaults
tblib                     1.3.2            py36h34cf8b6_0    defaults
tensorboard               1.7.0                     <pip>
tensorflow                1.7.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.6              py36ha25a19f_0    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
Theano                    1.0.1                     <pip>
tk                        8.6.7                h5979e9b_1    defaults
toolz                     0.8.2            py36h81f2dff_0    defaults
tornado                   4.5.2            py36h1283b2a_0    defaults
traitlets                 4.3.2            py36h674d592_0    defaults
typing                    3.6.2            py36h7da032a_0    defaults
tzlocal                   1.5.1                     <pip>
umap-learn                0.2.3                     <pip>
unicodecsv                0.14.1           py36ha668878_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
virtualenv                15.1.0                   py36_0    defaults
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
websocket-client          0.40.0                    <pip>
Werkzeug                  0.14.1                    <pip>
werkzeug                  0.12.2           py36hc703753_0    defaults
wheel                     0.31.0                    <pip>
wheel                     0.29.0           py36he7f4e38_1    defaults
widgetsnbextension        3.0.2            py36hd01bb71_1    defaults
wrapt                     1.10.11          py36h28b7045_0    defaults
xlrd                      1.1.0            py36h1db9f0c_1    defaults
xlsxwriter                1.0.2            py36h3de1aca_0    defaults
xlwt                      1.3.0            py36h7b00a1f_0    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zeromq                    4.2.2                hb0b69da_1    defaults
zict                      0.1.3            py36h3a3bf81_0    defaults
zlib                      1.2.11               hfbfcf68_1    defaults

```

**Comment by hufangjian** [comment]
1. cd  /etc/ld.so.conf.d
2. vim anaconda.conf   and add /root/anaconda3/lib
3. ldconfig -v

**Comment by durack1** [comment]
@mingwandroid this occurred for me today, even though I had just updated conda (to 4.5.4-py27_0). I wonder if the problem is now back and this issue should be reopened?

**Comment by tshead2** [comment]
I've run into this issue with Travis CI ... during regression testing I get the following when importing scipy, installed using miniconda.

The OS provided by Travis is Ubuntu 14.04.5 LTS.  From there, I'm installing conda 4.5.8, and creating a test environment using Python 3.6.6.  Full details at https://travis-ci.org/sandialabs/samlab/builds/405475819

Not sure whether this is a conda issue or Ubuntu 14 showing its age.  Any suggestions welcome.

Thanks in advance,
Tim

```
      Traceback (most recent call last):
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/examples.py", line 15, in step_impl
          samlab.example.iris.create(context.database, context.fs)
        File "/home/travis/build/sandialabs/samlab/samlab/example/iris.py", line 33, in create
          import sklearn.datasets
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sklearn/__init__.py", line 134, in <module>
          from .base import clone
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sklearn/base.py", line 11, in <module>
          from scipy import sparse
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 229, in <module>
          from .csr import *
        File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
          from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
      ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by mingwandroid** [comment]
I cannot reproduce this, but I suspect one of your PIP installed dependencies is being imported before scipy is linking to your system libstdc++ and that prevents our libstdc++ from being used.

I can't really do much about PIP binaries, it's kind of like the wild-west of package building over there.

**Comment by mingwandroid** [comment]
BTW we do fully support ubuntu 14.04 at present.

**Comment by shuvamklu** [comment]
> There is an issue in anaconda where libstdc++ is not linking to version 6.0.24 but rather to 6.0.19. If you manually relink libstdc++.so and libstdc++.so.6 to libstdc++.so.6.0.24 it should work.

how to relink manually?????

**Comment by mingwandroid** [comment]
@shuvamklu, please ignore that comment it is incorrect.

**Comment by thebillkidy** [comment]
Just for everyone else having the problem, here the solution:
* libstdc++ is located in /home/<YOUR_USER>/anaconda3/libstdc++.so.6.0.25 (in my case)
* Remove old links and link the there :)

example:

```bash
rm /home/<YOUR_USER>/anaconda3/lib/libstdc++.so.6.0.21
ln -s /home/<YOUR_USER>/anaconda3/lib/libstdc++.so.6.0.25 /home/<YOUR_USER>/anaconda3/lib/libstdc++.so.6.0.21
```

**Comment by morawi** [comment]
That did not help at all, 1) running `apt-get update` to update all the package lists,
followed by `apt-get upgrade` to update all the installed software to the latest versions and,
2) running `pip install opencv-contrib-python` solved the problem.

**Comment by agrija9** [comment]
For those facing this issue under linux CentOS, the solution of this thread worked for me: https://stackoverflow.com/questions/48831881/centos-7-libstdc-so-6-version-cxxabi-1-3-9-not-found
