### ISSUE TITLE
Missing Start Menu item after installing Anaconda 2.4.1

### ISSUE THREAD

**Issue by stenci** [ContinuumIO/anaconda-issues#614]
After executing "Anaconda3-2.3.0-Windows-x86.exe" the Start Menu items are available, but after installing "Anaconda3-2.4.1-Windows-x86.exe" they are missing.
I found [some issues](https://github.com/ContinuumIO/anaconda-issues/search?q=start+menu&type=Issues&utf8=%E2%9C%93) related to Miniconda, none related to the latest version of Anaconda. The installer for both says they will be installed.
Is this a regression?

**Comment by msarahan** [comment]
This issue has been reported on the mailing list, but not here yet.

On the mailing list, the cause was found to be a strange windows race condition. A fix is in the works and should be released soon, along with instructions on how to restore icons.

**Comment by mkoske** [comment]
I probably have this same issue too. I downloaded 64bit Anaconda 3 and installed it but there's no shortcuts available anywhere. I'm on Windows 8.1., so there's no traditional start menu, but same issue still.

**Comment by msarahan** [comment]
These issues have hopefully been addressed with Menuinst version 1.3.2, which is available now.  To install menu shortcuts, please go to a command prompt and type the following commands:

    conda update menuinst
    conda install -f console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder

Closing this issue.  Please reopen or open a separate issue if problems recur.

**Comment by stenci** [comment]
Are you saying that Menuinst is available and one can use it as a workaround to the installer problem?
Or has the installer (which states it will create the menu automatically) been fixed?

**Comment by msarahan** [comment]
The installer uses menuinst behind the scenes.  We can't go back and change
the old installer.  We are scheduled to have new installers in February.
Until then, these two commands should restore functionality for you.

**Comment by olivier65** [comment]
We are now in March and the new installer still doesn't create Startup Menu items.

**Comment by msarahan** [comment]
@olivier65 could you be more specific?  What installer are you using?  We did fix one class of problems with the 2.5 installer, but perhaps not the one causing your issue.  Do you see any error messages?  If so, what do they say?  Can you post screenshots or copy/paste error messages?

We have fixed one further potential problem since the 2.5 release, where a Python installation other than the new one was used in bootstrapping.  Do you have other Python installations?

We have a new release coming soon.  If you'd be willing to help us beta-test it, I'd appreciate your help in making sure that we fix the issue you're having.

**Comment by olivier65** [comment]
I was using the Miniconda-latest-Windows-x86_64 installer, downloaded the 11 March. No error messages, the Startup Menu items simply weren't created.

**Comment by msarahan** [comment]
There are no start menu shortcuts created by the Miniconda installer.  This is not a bug.  None of the packages that it includes have shortcuts.  You get shortcuts by installing packages that have them.  This is a pretty short list:

    console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder

Out of curiosity, what shortcuts were you expecting to see?

**Comment by olivier65** [comment]
In the screen where it offers to add Conda to PATH it tells you that if you don't you will have to start conda using the cmd shortcut in the Anaconda menu and I did decline to have conda added to PATH, so I expected that shortcut at least.

**Comment by mingwandroid** [comment]
To me that soounds like a documentation bug (in miniconda itself, rather than the docs). IMHO miniconda should be as minimal as possible.

In this case it should say that you will need to add it to your PATH environment variable yourself either in Windows globally or in each cmd.exe/Powershell invocation.

Does that sound reasonable?

**Comment by olivier65** [comment]
Adding it to the PATH is undesirable if there are other pythons around. If it won't create the cmd shortcut the installer or the docs should at least include the info in this thread.

**Comment by msarahan** [comment]
@olivier65 is right.  I think this is a bug in that the console_shortcut package should be getting installed, but either is not functioning correctly, or is not being included.  Thanks for the report.  I think it belongs in a new issue.  I will create one.

**Comment by ns96** [comment]
This issue still occurs with Anaconda3-4.0.0-Windows-x86_64.exe installing on Windows 7 Home Edition Service Pack 1, verified this twice. 

Using the manual command above those put the menu items in place, but for newbie, this kinda defeats the whole point of having a GUI installer.

**Comment by x0lani** [comment]
I'm having this issue on Anaconda3-4.0.0-Windows-x86_64.exe as well.  However, I found that if I begin by right-clicking the installer and "Run as Administrator", the icons appear. My guess is that the race condition has to do with not having admin rights to install for all users when the time to install links occurs.

**Comment by rmlopes** [comment]
That is a good catch @x0lani. I don't require this feature, nevertheless I have been re-installing Anaconda3 in my machines for all users (so it should run in Admin mode, correct?) and it does not create the menus as well.

**Comment by Joulious** [comment]
As of right now, Anaconda3 doesn't create shortcuts on a Win10 x64 system.

**Comment by humanfactors** [comment]
Can confirm issue as well on Windows 8.1 installation. No shortcuts or menu items. In fact, GUI missing from installation directory altogether.

**Comment by nyngwang** [comment]
Anaconda3 5.1.0 (64-bit) Windows10, the same issue when I select "for all users"

**Comment by nyngwang** [comment]
Ok, I changed the directory from the default, i.e. C:\ProgramData\Anaconda3), to C:\Anaconda3 and it works.

**Comment by truedat101** [comment]
@lk911 This looks like the same problem we are looking at on your windows 10.

**Comment by shrokmel** [comment]
I am having the same issue with Anaconda3 5.2.0 (64-bit) Windows10, for single user. Only the Anaconda Command Prompt is appearing in the shortcuts. The Anaconda navigator, or conda, seems to be not available anywhere, including the installed directory.

**Comment by truedat101** [comment]
@shrokmel I will try installing 5.1.0 to see if this problem existed in the previous version on Win10 64bit.

**Comment by truedat101** [comment]
@shrokmel I've created a new issue #9595 to track this, but I think we need to provide more details on a sure fire way to reproduce.

**Comment by mhallak** [comment]
As of today, I tried to install miniconda on windows 10, as an administrator, not as an administrator, with reboot and without reboot, trying: 
conda update menuinst
conda install -f console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder
and experiencing exactly the same issues as mentioned above (by @SakshiShreya )...

But I now installed anaconda (and not mini) and everything is fine: there is a shortcut to the anaconda-navigator!
