### ISSUE TITLE
BUG: LinAlgError raised by scipy.linalg.svd for valid matrix

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#695]
_From @Eric89GXL on March 11, 2016 20:42_

There is some bug in Anaconda's build of `scipy` that causes a `LinAlgError` to be raised when computing SVDs using MKL. They happen frequently to me when doing SVDs of large matrices. The matrices do not have `inf` or `nan` in them, and I [have](https://github.com/numpy/numpy/issues/1588) read [some](https://github.com/scipy/scipy/issues/3868) relevant [issues](https://github.com/scipy/scipy/issues/4994).

Bad file located [here](https://staff.washington.edu/larsoner/bad.npy). Code to reproduce, assuming `numpy` (1.10.4), `scipy` (0.17), and `mkl` (11.3.1) are all installed:

```
from scipy import linalg
import numpy as np
bad = np.load('bad.npy')
linalg.svd(bad)
```

This error does not occur with OpenBLAS numpy/scipy installed via `conda`.

I have built my own versions of `numpy` and `scipy` linked to MKL from source, and I cannot reproduce the error.

If someone can share the `site.cfg` (and any other changes) that Anaconda uses to build with MKL as well as the Intel release version, I'm happy to see if I can reproduce the errors and maybe do some debugging/isolating myself.

_Copied from original issue: conda/conda#2244_

**Comment by kalefranz** [comment]
_From @mcg1969 on March 11, 2016 20:44_

This probably needs to be moved to Anaconda's issue page.

**Comment by insertinterestingnamehere** [comment]
I'm having trouble reproducing this on Windows, Linux, or OSX. Can you give us a little more information about the system you're using?

**Comment by Eric89GXL** [comment]
Ubuntu 15.10, although I think my colleagues have the same problem on
14.04. I'll try to create a compete minimal example using miniconda.

**Comment by kambysese** [comment]
@insertinterestingnamehere exactly what kind of information do you need because I can reproduce the error with the above minimal on OSX 

conda info returns:

> platform : osx-64
>  conda version : 3.19.0
>  conda-build version : 1.18.1
>  python version : 2.7.11.final.0
>  requests version : 2.9.1
>  root environment : /Users/ktavabi/anaconda  (writable)
>   default environment : /Users/ktavabi/anaconda
>   envs directories : /Users/ktavabi/anaconda/envs
>   package cache : /Users/ktavabi/anaconda/pkgs
>   channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
>   https://repo.continuum.io/pkgs/free/noarch/
>  https://repo.continuum.io/pkgs/pro/osx-64/
>   https://repo.continuum.io/pkgs/pro/noarch/
>   config file : None
>   is foreign system : False

**Comment by insertinterestingnamehere** [comment]
This is odd. I've tried with Python 2.7/3.5 on OSX 10.10, and Ubuntu 15.10 with a Haswell CPU and with Python 2.7/3.5 on Windows with an Ivy Bridge CPU and seen nothing thus far. Maybe it's architecture specific...?

**Comment by Eric89GXL** [comment]
I've also had the problem on Travis before and had to skip tests because of
it. I'll see if I can replicate there, too.

**Comment by insertinterestingnamehere** [comment]
We did just recently update the gfortran version that we're using. If you aren't using the latest build numbers for numpy and scipy I could see something like this coming up. That would explain the Linux errors, but not the OSX ones.

**Comment by Eric89GXL** [comment]
It should build with ifort, not gfortran, though...?

**Comment by mcg1969** [comment]
Yes, that's right

**Comment by Eric89GXL** [comment]
Here you go (note that the `sed` line is because `conda` by default will use system packages, and my bleeding-edge build of `numpy` will cause problems without it -- but none of my colleauges have this setup so it shouldn't be the issue):
```Bash
larsoner@bunk:~$ mkdir temp
larsoner@bunk:~$ cd temp/
larsoner@bunk:~/temp$ wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
larsoner@bunk:~/temp$ chmod +x miniconda.sh
larsoner@bunk:~/temp$ ./miniconda.sh -b -p ./miniconda
PREFIX=/home/larsoner/temp/miniconda
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
installing: conda-env-2.4.5-py27_0 ...
installing: openssl-1.0.2d-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.19.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
installing: pip-7.1.2-py27_0 ...
installing: wheel-0.26.0-py27_1 ...
installing: setuptools-18.8.1-py27_0 ...
Python 2.7.11 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
larsoner@bunk:~/temp$ export PATH=$PWD/miniconda/bin:$PATH
larsoner@bunk:~/temp$ which conda
/home/larsoner/temp/miniconda/bin/conda
larsoner@bunk:~/temp$ which python
/home/larsoner/temp/miniconda/bin/python
larsoner@bunk:~/temp$ conda install numpy scipy mkl
Fetching package metadata: ....
Solving package specifications: .....................
Package plan for installation in environment /home/larsoner/temp/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.1                 |                0       121.2 MB
    mkl-rt-11.1                |               p0       100.1 MB
    openssl-1.0.2g             |                0         3.2 MB
    sqlite-3.9.2               |                0         3.9 MB
    numpy-1.10.2               |          py27_p0         5.9 MB
    requests-2.9.1             |           py27_0         605 KB
    setuptools-20.2.2          |           py27_0         453 KB
    wheel-0.29.0               |           py27_0          81 KB
    conda-4.0.4                |           py27_0         184 KB
    pip-8.1.0                  |           py27_0         1.5 MB
    scipy-0.16.1               |     np110py27_p0        23.9 MB
    ------------------------------------------------------------
                                           Total:       261.0 MB

The following NEW packages will be INSTALLED:

    mkl:        11.3.1-0           
    mkl-rt:     11.1-p0            
    numpy:      1.10.2-py27_p0      [mkl]
    scipy:      0.16.1-np110py27_p0 [mkl]

The following packages will be UPDATED:

    conda:      3.19.0-py27_0 --> 4.0.4-py27_0       
    openssl:    1.0.2d-0      --> 1.0.2g-0           
    pip:        7.1.2-py27_0  --> 8.1.0-py27_0       
    requests:   2.9.0-py27_0  --> 2.9.1-py27_0       
    setuptools: 18.8.1-py27_0 --> 20.2.2-py27_0      
    sqlite:     3.8.4.1-1     --> 3.9.2-0            
    wheel:      0.26.0-py27_1 --> 0.29.0-py27_0      

Proceed ([y]/n)? 

Fetching packages ...
<snip>
larsoner@bunk:~/temp$ wget -q https://staff.washington.edu/larsoner/bad.npy
larsoner@bunk:~/temp$ python -c "from scipy import linalg; import numpy as np; bad = np.load('bad.npy'); linalg.svd(bad);"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+ec5bd81-py2.7-linux-x86_64.egg/numpy/__init__.py", line 201, in <module>
    from . import random
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+ec5bd81-py2.7-linux-x86_64.egg/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+ec5bd81-py2.7-linux-x86_64.egg/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
larsoner@bunk:~/temp$ sed -i "s/ENABLE_USER_SITE = .*/ENABLE_USER_SITE = False/g" ./miniconda/lib/python2.7/site.py
larsoner@bunk:~/temp$ python -c "from scipy import linalg; import numpy as np; bad = np.load('bad.npy'); linalg.svd(bad);"
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 107, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
larsoner@bunk:~/temp$ python -c "import numpy; print(numpy, numpy.__version__); import scipy; print(scipy, scipy.__version__)"
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
(<module 'numpy' from '/home/larsoner/temp/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>, '1.10.2')
(<module 'scipy' from '/home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/__init__.pyc'>, '0.16.1')
```

**Comment by Eric89GXL** [comment]
Perhaps here is some hint.

1. I have been trying to recreate this on Travis, but it passes without warning about using MKL at all, which is strange:

  https://travis-ci.org/Eric89GXL/bad/builds/115463610
  https://travis-ci.org/Eric89GXL/bad/builds/115463420

  If I have it print the `numpy` config, I can confirm that it appears to use MKL, even though it does not warn about the 30-day license:

  https://travis-ci.org/Eric89GXL/bad/builds/115465923

  Did you all remove the 30-day license warning?

2. Then if I use a different install path (without `conda update conda`) that does warn about MKL 30-day licensing, it complains about not being able to find `libgfortran`:

  https://travis-ci.org/Eric89GXL/bad/builds/115465359

  And I can confirm that this version also uses MKL using `numpy.show_config()`:

  https://travis-ci.org/Eric89GXL/bad/builds/115465713

  So I can't seem to recreate the problem on Travis right now, which is a bummer.

3. I'm a bit confused why it needs `libgfortran` if compiling with `ifort`. When I do `ldd` on my self-compiled version of `scipy/linalg/_fblas.so` (granted from a newer/0.18-dev `scipy` commit), I see no `libgfortran.so` links (hex removed):
  ```
larsoner@bunk:~/temp$ ldd ~/.local/lib/python2.7/site-packages/scipy/linalg/_fblas.so 
	linux-vdso.so.1 =>
	libmkl_rt.so => /opt/intel/mkl/lib/intel64/libmkl_rt.so
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
	libifport.so.5 => /opt/intel/lib/intel64/libifport.so.5
	libifcore.so.5 => /opt/intel/lib/intel64/libifcore.so.5
	libimf.so => /opt/intel/lib/intel64/libimf.so
	libsvml.so => /opt/intel/lib/intel64/libsvml.so
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
	libintlc.so.5 => /opt/intel/lib/intel64/libintlc.so.5
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
	/lib64/ld-linux-x86-64.so.2
  ```

  When I look at Anaconda's version, it links to `libgfortran.so.3`:
  ```
larsoner@bunk:~/temp$ ldd miniconda/lib/python2.7/site-packages/scipy/linalg/_fblas.so 
	linux-vdso.so.1 =>
	libmkl_intel_lp64.so => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libmkl_intel_lp64.so
	libmkl_intel_thread.so => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libmkl_intel_thread.so
	libmkl_core.so => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libmkl_core.so
	libiomp5.so => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libiomp5.so
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
	libpython2.7.so.1.0 => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libpython2.7.so.1.0
	libgfortran.so.3 => /home/larsoner/temp/miniconda/lib/python2.7/site-packages/scipy/linalg/../../../../libgfortran.so.3
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
	/lib64/ld-linux-x86-64.so.2
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1
  ```
  Is `scipy` being built with `gfortran` instead of `ifort`, or is this an older-version-of-scipy thing?

**Comment by kambysese** [comment]
@insertinterestingnamehere this may no longer be relevant but I also rep the error on my linux box which has following specs:

> 24x Intel Xeon X5660 @ 2.8GHz
> Ubuntu 14.04.4

and Anaconda Accelerate environment:

> conda version : 3.19.3
> conda-build version : 1.18.2
> python version : 2.7.11.final.0
> requests version : 2.9.1
> config file : None
> mkl-rt  11.1 p0
> mkl-service 1.1.0  py27_p0
> numpy 1.10.2 py27_p0  [mkl]
> scipy 0.16.1 np110py27_p0  [mkl]

**Comment by insertinterestingnamehere** [comment]
Thanks for the info. I'm taking another shot at reproducing it now.
To answer your questions thus far:

1. Yes, we no longer require a license for MKL. Intel opted to freely distribute MKL, so we've started shipping it with Anaconda by default. If, for licensing reasons, you don't want to use a proprietary BLAS/LAPACK implementation, there are ways to use OpenBLAS instead. Ilan wrote a nice blog post about it [here](https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations).
2. You can install older debug releases of numpy and scipy by fixing libgfortran=1.0 in your conda install. The simplest thing to do is to install the latest bugfix release for the version you're supporting though. We've already had some discussion of issues like this at https://github.com/scipy/scipy/issues/5917 (among others). If you need older bugfix releases, the best thing to do, for now, is specify libgfortran=1.0.
3. We currently use gfortran to compile the default numpy and scipy on Linux. There has been some discussion about using ifort for some builds there, but that's not at all a settled matter and the default channels don't currently use it.

**Comment by insertinterestingnamehere** [comment]
The fact that conda installs the old non-free mkl version when you do `conda install numpy scipy mkl` is a bug, but it looks like it was already fixed with the latest conda.

**Comment by Eric89GXL** [comment]
Makes sense, thanks for helping with this. I'll see if I can get a failure
on Travis using libgfortan=1.0, and also see if I can get something
reproducible on my windows and OSX machines.

**Comment by Eric89GXL** [comment]
Travis is okay with the old version, too:

https://travis-ci.org/Eric89GXL/bad/builds/115697264

Worked okay on my Windows box, too. Time to try OSX...

**Comment by Eric89GXL** [comment]
Couldn't replicate on OSX. I can (re)confirm that I do get the error on my Linux with up-to-date `conda`, both when using up-to-date `scipy` (with `libgfortran=3.0`) and when using `libgfortran=1.0` (and thus `scipy=0.17.0, np110py27_0`).

@insertinterestingnamehere perhaps you are right that this is architecture-dependent. Not sure the best path forward here, but:

- My CPU is Intel 980x Nehalem, which only supports up to SSE4.2 instruction set. 
- @insertinterestingnamehere you have Haswell, which supports AVX(2) with FMA, which I have to imagine MKL would make use of.
- @kambysese IIRC is using Xeon processors probably *before* built before the Sandy-bridge generation (where IIUC they added AVX), so he's probably also using SSE4.2 only.

@kambysese what is your CPU? `cat /proc/cpuinfo` will get you the model number at least. From there, maybe we can confirm it has up through SSE4.2 only. You can also try `cat /proc/cpuinfo | grep avx | wc -l` and see if it gives a value > 0. For me the related command `cat /proc/cpuinfo | grep sse4_2 | wc -l` gives 12 (for the 6 hyperthreaded cores), but 0 for the `... | grep avx ...` version.

Either way, I don't get these errors when I compile myself using `icc` and `ifort`. @insertinterestingnamehere if it's possible for someone over there to compile a version with `ifort` instead of `gfortran` I'm happy to install and try it. Or if you can get me the Intel compiler version you're using, I can try to do it myself to see if I can replicate it. I am currently using the latest release, and I could try not using `ifort` to see if it breaks...?

**Comment by insertinterestingnamehere** [comment]
I'll defer to @ilanschnell with regards to putting together ifort based builds. I don't have a build box set up for doing that right now and I don't know what the long term plans are there.
Looking through the MKL 11.3 release notes, it appears they officially only support using it with gfortran 4.9 and later. It could be worth trying to put together builds with the new gcc 5.2 toolchain from @msarahan to see if that fixes it. It'd be really helpful if someone could try reproducing this. @groutr @msarahan @ilanschnell?

**Comment by insertinterestingnamehere** [comment]
I don't see this on a Penryn machine in Windows or a Linux VM. That's the SSE 4.1 instruction set.

**Comment by kambysese** [comment]
Using the miniconda recipe from above I can reproduce this on a MacBookPro11,3 with an [Intel Core i7](http://ark.intel.com/m/products/47922/Intel-Xeon-Processor-X5650-12M-Cache-2_66-GHz-6_40GTs-Intel-QPI#@product/specifications) using the SSE4.2 instruction set.

```
  cd Desktop/
  mkdir tmp
  cd tmp
  curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh
  chmod +x miniconda.sh
  ./miniconda.sh -b -p ./miniconda
  export PATH=$PWD/miniconda/bin:$PATH
  which conda
    /Users/ktavabi/Desktop/tmp/miniconda/bin/conda
  which python
    /Users/ktavabi/Desktop/tmp/miniconda/bin/python
  conda install numpy scipy mkl
  curl https://staff.washington.edu/larsoner/bad.npy > bad.npy
  python -c "from scipy import linalg; import numpy as np; bad = np.load('bad.npy'); linalg.svd(bad);"  
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/ktavabi/Desktop/tmp/miniconda/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 107, in svd
        raise LinAlgError("SVD did not converge")
    numpy.linalg.linalg.LinAlgError: SVD did not converge
```

**Comment by Eric89GXL** [comment]
Opened an issue with the Intel folks for a related error:

https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/628049

I'm opening that one with them because I found a different array for which I get the "SVD did not converge" error on my locally-built SciPy but *not* on Anaconda SciPy. FWIW I also got an `lapack_driver` argument added to `linalg.svd` so that there will at least be an ugly workaround once SciPy 0.18 comes out:

https://github.com/scipy/scipy/pull/5994

Let me know if there is anything I can do to help move forward investigation on the Anaconda end for the other array mentioned above that fails. If it's possible to get e.g. the `site.cfg` for NumPy and/or any other changes that need to be made to NumPy and SciPy to build them "the Anaconda way" I'd be happy to work with it and see what I can find.

**Comment by Eric89GXL** [comment]
Great news -- the Intel folks could replicate the issue with the same array that Anaconda currently fails on, and they report that it is fixed by the current pre-release version of MKL 11.3.3:

https://software.intel.com/en-us/comment/1869912#comment-1869912

So hopefully once they push out that new version, Anaconda can be fixed. Do you all keep up to date with new versions of MKL and/or parallel studio when they come out?

**Comment by insertinterestingnamehere** [comment]
Thanks for following up on this one a bit more. Letting Intel know about it was definitely a great idea. We can leave this issue open until we update the version of MKL that we ship as well.

**Comment by Eric89GXL** [comment]
Okay, I have another matrix -- [this one] (https://staff.washington.edu/larsoner/bad_avx.npy) passes on my machine (SSE4.2 only) but fails on a machine with AVX and up-to-date Anaconda. @insertinterestingnamehere can you replicate with this one?

**Comment by Eric89GXL** [comment]
@insertinterestingnamehere do you have time to test [this matrix] (https://staff.washington.edu/larsoner/bad_avx.npy) to see if it fails on your AVX hardware, like:
```
python -c "import numpy as np; from scipy.linalg import svd; svd(np.load('bad_avx.npy'), full_matrices=False)"
```
That could help bolster the case for Intel to take a closer look, since it is a failure that happens on more hardware.

**Comment by insertinterestingnamehere** [comment]
Sorry, I sometimes miss github notifications. I need to unfollow some things. I currently only have to my ivy bridge machine. Thus far, the latest matrix comes up clean on Windows and virtualized Linux there. I'll try without virtualization as well.

**Comment by yaroslavvb** [comment]
BTW, I just ran into similar issue, below is a self-contained repro. It passes on MacBook, but fails on Xeon V4 with "SVD did not converge"
```
import scipy.linalg as linalg
import numpy as np

def download_if_needed(fn,target_length=0,bucket="yaroslavvb_stuff"):
  import urllib.request
  url="https://storage.googleapis.com/%s/%s"%(bucket, fn)
  response = urllib.request.urlopen(url)
  body = response.read()
  print("Read %d bytes"%(len(body),))
  if target_length:
    assert len(body)==target_length
    
  open(fn, "wb").write(body)

fn='badsvd0'
download_if_needed(fn, 2458624)
target0 = np.fromfile(fn, np.float32).reshape(784,784)
u0, s0, vt0 = linalg.svd(target0)
print("Success")

```

**Comment by Eric89GXL** [comment]
I'm pretty sure this is Intel's problem. It would be great if you could comment here and/or try to replicate with some of my matrices:

https://software.intel.com/en-us/comment/1869912

**Comment by yaroslavvb** [comment]
@Eric89GXL I tried your matrix at top of the file, and also kaby_lake example and it worked for me. My example fails on Xeon V3 but passes on Xeon V4 and 2015 macbook

**Comment by yaroslavvb** [comment]
@Eric89GXL btw, thanks for adding the Lapack driver argument, that fixes my issue on our Xeon V3's. New method gesvd takes 3x longer, but at least I can run it in "try/catch" when gesdd fails.

**Comment by yaroslavvb** [comment]
So Intel was able to reproduce my failure, and recommended lowering number of threads to 15 using `MKL_NUM_THREADS=15`. I wonder if there an acceptable way of doing this from within Python? IE
```
try:
  linalg.svd(...)
except:
  # lower number of threads
  linalg.svd(...)
  # raise number of threads

```
Right now, my work-around is this, but gesvd runs 3x slower than default:


```
    try:
      u0, s0, vt0 = linalg.svd(target0)
      v0 = vt0.T
    except Exception as e:
      print("gesdd failed, trying gesvd  %s"%(e,))
      u0, s0, vt0 = linalg.svd(target0, lapack_driver="gesvd")

```

**Comment by Eric89GXL** [comment]
I don't think there is a way to change the number of threads dynamically. AFAIK it can only be done once. I've been using the `gesvd` workaround (which I put in SciPy for this case) for ~6 months. Fortunately the errors are relatively rare for me, so the slowdown isn't problematic.

I'm glad you were able to reproduce, since it seems like your commenting on the Intel issue got them to look into it again!

**Comment by csoja** [comment]
Sounds like this is fixed with the latest MKL. Closing.

**Comment by larsoner** [comment]
> Sounds like this is fixed with the latest MKL. Closing.

Where have you seen this? Did you have the problem before and now it's gone?

I don't see a mention of it in the release notes:

https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-bug-fixes-list

I just updated to the latest version (`icc --version` gives `18.0.1 20171018`) and I still have a failure on my KabyLake system.

**Comment by csoja** [comment]
Apologies, I guess I have misread the issue comments - I had thought this "they report that it is fixed by the current pre-release version of MKL 11.3.3" - and the current MKL version in repo.continuum.io is much more recent than 11.3.3 - it is 2018.0.0.  Though as it is an upstream issue, I'm not sure that it really belongs in this issue tracker.  Reopening...
