### ISSUE TITLE
Possible bad library for 32-bit libpython27.a & libpython36.a

### ISSUE THREAD

**Issue by allyelsey** [ContinuumIO/anaconda-issues#7624]
An Enterprise customer reported this issue:

"My attempt to compile with 64 bit anaconda (Python, w/gfortran & numpy) has tested fine now on 2.7 & 3.6. However I am having a problem with the 32 bit build for both 32-bit platforms with the gfortran you distribute for Windows.

This command fails with lots of missing symbols:

C:\conda2-32\python.exe C:\conda2-32\Scripts\f2py.py -c fellipse.for -m fellipse DIFFaXsubs.a powsubs.a spsubs.a texturesubs.a --compiler=mingw32 --fcompiler=gfortran --f77flags="-fno-range-check"

such as:
```
c:\users\toby~1.win\appdata\local\temp\tmpa3hylo\Release\users\toby~1.win\appdata\local\temp\tmpa3hylo\src.win32-2.7\fellipsemodule.o:fellipsemodule.c:(.text+0x14): undefined reference to `_imp__PyFloat_Type'
c:\users\toby~1.win\appdata\local\temp\tmpa3hylo\Release\users\toby~1.win\appdata\local\temp\tmpa3hylo\src.win32-2.7\fellipsemodule.o:fellipsemodule.c:(.text+0x25): undefined reference to `_imp__PyType_IsSubtype'
c:\users\toby~1.win\appdata\local\temp\tmpa3hylo\Release\users\toby~1.win\appdata\local\temp\tmpa3hylo\src.win32-2.7\fellipsemodule.o:fellipsemodule.c:(.text+0x4a): undefined reference to `_imp__PyNumber_Float’
```

I am guessing that the problem is that libpython27.a is just about empty:

`(root) C:\Users\toby.WIN10-VM\Documents\fsource>dir \conda2-32\libs\*py*.a`

Directory of C:\conda2-32\libs

12/02/2017 07:55 PM 1,560 libpython27.a

Same problem with miniconda3. In contrast, here is what I see for 64 bit:

Directory of C:\conda2-64\libs

12/01/2017 04:46 PM 826,378 libpython27.a

You will probably want to see this stuff:

`(root) C:\Users\toby.WIN10-VM\Documents\fsource>conda info`

#Current conda install:
#
platform : win-32
conda version : 4.3.30
conda is private : False
conda-env version : 4.3.30
conda-build version : not installed
python version : 2.7.14.final.0
requests version : 2.18.4
root environment : C:\conda2-32 (writable)
default environment : C:\conda2-32
envs directories : C:\conda2-32\envs
C:\Users\toby.WIN10-VM\AppData\Local\conda\conda\envs
C:\Users\toby.WIN10-VM\.conda\envs
package cache : C:\conda2-32\pkgs
C:\Users\toby.WIN10-VM\AppData\Local\conda\conda\pkgs
channel URLs : https://repo.continuum.io/pkgs/main/win-32
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/win-32
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/win-32
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/win-32
https://repo.continuum.io/pkgs/pro/noarch
https://repo.continuum.io/pkgs/msys2/win-32
https://repo.continuum.io/pkgs/msys2/noarch
config file : None
netrc file : None
offline mode : False
user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.14393
administrator : False

`(root) C:\Users\toby.WIN10-VM\Documents\fsource>conda list`

# packages in environment at C:\conda2-32:
#
asn1crypto 0.23.0 py27h1d0b1e9_0
ca-certificates 2017.08.26 h94faf87_0
certifi 2017.11.5 py27h588676d_0
cffi 1.11.2 py27h591b45b_0
chardet 3.0.4 py27h400594b_1
conda 4.3.30 py27h55876ee_0
conda-env 2.6.0 h36134e3_1
console_shortcut 0.1.1 h6bb2dd7_3
cryptography 2.1.4 py27ha8a5bac_0
enum34 1.1.6 py27h62011c5_1
icc_rt 2017.0.4 h97af966_0
idna 2.6 py27hc92a076_1
intel-openmp 2018.0.0 hc0023dc_8
ipaddress 1.0.18 py27hdb5ba36_0
m2w64-binutils 2.25.1 5
m2w64-bzip2 1.0.6 6
m2w64-crt-git 5.0.0.4636.2595836 2
m2w64-gcc 5.3.0 6
m2w64-gcc-fortran 5.3.0 6
m2w64-gcc-libgfortran 5.3.0 6
m2w64-gcc-libs 5.3.0 7
m2w64-gcc-libs-core 5.3.0 7
m2w64-gmp 6.1.0 2
m2w64-headers-git 5.0.0.4636.c0ad18a 2
m2w64-isl 0.16.1 2
m2w64-libiconv 1.14 6
m2w64-libwinpthread-git 5.0.0.4634.697f757 2
m2w64-mpc 1.0.3 3
m2w64-mpfr 3.1.4 4
m2w64-windows-default-manifest 6.4 3
m2w64-winpthreads-git 5.0.0.4634.697f757 2
m2w64-zlib 1.2.8 10
menuinst 1.4.10 py27hffda999_0
mkl 2018.0.1 h1db664d_4
msys2-conda-epoch 20160418 1
numpy 1.13.3 py27hfa60546_0
openssl 1.0.2m h05bc326_1
pip 9.0.1 py27hfe60e39_4
pycosat 0.6.3 py27hd462980_0
pycparser 2.18 py27h9852578_1
pyopenssl 17.5.0 py27h68a058b_0
pysocks 1.6.7 py27h3e65130_1
python 2.7.14 hca1081f_23
pywin32 221 py27hd388f4c_0
requests 2.18.4 py27h038ddc7_1
ruamel_yaml 0.11.14 py27h6ffe8f8_2
scons 3.0.0 py27h48b8cb6_0
setuptools 36.5.0 py27h474e7f7_0
six 1.11.0 py27hcc62b61_1
urllib3 1.22 py27h0db6be9_0
vc 9 h7299396_1
vs2008_runtime 9.00.30729.1 hfaea7d5_1
wheel 0.30.0 py27hf092909_1
win_inet_pton 1.0.1 py27h4f1e666_1
wincertstore 0.2 py27h87a2792_0
yaml 0.1.7 h00170ee_2
"

**Comment by mingwandroid** [comment]
This is fixed now.

**Comment by jgmorrison** [comment]
Sorry to report this still seems to be a problem, at least with Python3. I will try out conda2 now.

Process:
I did a fresh 32-bit miniconda3 install. Then did

conda update —all

and

conda install m2w64-gcc-fortran svn numpy scons

my build still fails with tons of undefined symbols.Also, libpython36.a is still tiny:

(c:\conda3) C:\Users\toby.WIN10-VM\GSASII\fsource>dir \conda3\libs
Volume in drive C is Windows
Volume Serial Number is CA22-5DF7

Directory of C:\conda3\libs

01/04/2018 04:24 PM <DIR> .
01/04/2018 04:24 PM <DIR> ..
01/04/2018 04:24 PM 1,546 libpython36.a
01/04/2018 04:24 PM 63,178 libvcruntime140.a
11/08/2017 06:13 PM 171,786 python3.lib
01/04/2018 04:24 PM 121 python36.def
11/08/2017 06:12 PM 324,094 python36.lib
11/08/2017 06:13 PM 1,746 _tkinter.lib
6 File(s) 562,471 bytes
2 Dir(s) 227,883,479,040 bytes free


(c:\conda3) C:\Users\toby.WIN10-VM\GSASII\fsource>conda info

active environment : base
active env location : c:\conda3
user config file : C:\Users\toby.WIN10-VM\.condarc
populated config files :
conda version : 4.4.6
conda-build version : not installed
python version : 3.6.3.final.0
base environment : c:\conda3 (writable)
channel URLs : https://repo.continuum.io/pkgs/main/win-32
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/win-32
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/win-32
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/win-32
https://repo.continuum.io/pkgs/pro/noarch
https://repo.continuum.io/pkgs/msys2/win-32
https://repo.continuum.io/pkgs/msys2/noarch
package cache : c:\conda3\pkgs
C:\Users\toby.WIN10-VM\AppData\Local\conda\conda\pkgs
envs directories : c:\conda3\envs
C:\Users\toby.WIN10-VM\AppData\Local\conda\conda\envs
C:\Users\toby.WIN10-VM\.conda\envs
platform : win-32
user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
administrator : False
netrc file : None
offline mode : False


(c:\conda3) C:\Users\toby.WIN10-VM\GSASII\fsource>conda list
# packages in environment at c:\conda3:
#
apr 1.6.3 h405b085_0
asn1crypto 0.23.0 py36h0057936_0
ca-certificates 2017.08.26 h94faf87_0
certifi 2017.11.5 py36h2c9f8ed_0
cffi 1.11.2 py36h3166483_0
chardet 3.0.4 py36hf2a9688_1
conda 4.4.6 py36_0
conda-env 2.6.0 h36134e3_1
console_shortcut 0.1.1 h6bb2dd7_3
cryptography 2.1.4 py36hd94e34c_0
expat 2.2.5 h015c98a_0
icc_rt 2017.0.4 h97af966_0
idna 2.6 py36h787667b_1
intel-openmp 2018.0.0 hc0023dc_8
m2w64-binutils 2.25.1 5
m2w64-bzip2 1.0.6 6
m2w64-crt-git 5.0.0.4636.2595836 2
m2w64-gcc 5.3.0 6
m2w64-gcc-fortran 5.3.0 6
m2w64-gcc-libgfortran 5.3.0 6
m2w64-gcc-libs 5.3.0 7
m2w64-gcc-libs-core 5.3.0 7
m2w64-gmp 6.1.0 2
m2w64-headers-git 5.0.0.4636.c0ad18a 2
m2w64-isl 0.16.1 2
m2w64-libiconv 1.14 6
m2w64-libwinpthread-git 5.0.0.4634.697f757 2
m2w64-mpc 1.0.3 3
m2w64-mpfr 3.1.4 4
m2w64-windows-default-manifest 6.4 3
m2w64-winpthreads-git 5.0.0.4634.697f757 2
m2w64-zlib 1.2.8 10
menuinst 1.4.10 py36h07c0980_0
mkl 2018.0.1 h1db664d_4
msys2-conda-epoch 20160418 1
numpy 1.13.3 py36h38e73f1_0
openssl 1.0.2n h74b6da3_0
pip 9.0.1 py36had87c14_4
pycosat 0.6.3 py36hbfdb8c3_0
pycparser 2.18 py36h315bf61_1
pyopenssl 17.5.0 py36h98b3c51_0
pysocks 1.6.7 py36hbb234f4_1
python 3.6.3 h52e1c9f_4
pywin32 221 py36heebab90_0
requests 2.18.4 py36h964142b_1
ruamel_yaml 0.11.14 py36h1a6402c_2
scons 3.0.0 py36_1
serf 1.3.9 hb3bc723_0
setuptools 36.5.0 py36h7f22f53_0
six 1.11.0 py36h7f2c006_1
sqlite 3.20.1 h85f533e_2
svn 1.9.7 h5e31a3b_0
urllib3 1.22 py36hf0c4117_0
vc 14 h2379b0c_2
vs2015_runtime 14.0.25123 hd4c4e62_2
wheel 0.30.0 py36h1201a8d_1
win_inet_pton 1.0.1 py36h6b5aef5_1
wincertstore 0.2 py36hcdd9a18_0
yaml 0.1.7 h896c600_2
zlib 1.2.11 hbb18732_2

**Comment by mingwandroid** [comment]
> conda install m2w64-gcc-fortran svn numpy scons

It looks like you didn't install the `libpython` package here. I believe the very small `libpython27.a` you saw is created (badly) by `f2py` when it fails to find the correct one from `libpython` (which is called `libpython27.dll.a`, and, for 32-bit Windows is 868,528 bytes big). Also, I would just install `m2w64-toolchain` to guarantee you have a complete toolchain (but for this testcase that is not necessary).

Here's what worked for me just now:

```
cd %TEMP%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe', 'mc2.exe') }"
start /wait "" mc2.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\mc2
%TEMP%\mc2\Scripts\activate.bat
conda install -y numpy m2w64-toolchain libpython
echo.      > test.f
echo       subroutine greetings() >> test.f
echo.      >> test.f
echo            print*, 'Hello, world! I am Fortran!' >> test.f
echo.      >> test.f
echo       end subroutine greetings >> test.f
f2py -c test.f -m helloworld_fortran --compiler=mingw32 --fcompiler=gfortran --f77flags="-fno-range-check"
```

.. you should see something like:

```
call "C:\Users\builder\AppData\Local\Temp\mc2\Scripts\\..\python.exe" "C:\Users\builder\AppData\Local\Temp\mc2\Scripts\\f2py.py" -c test.f -m helloworld_fortran --compiler=mingw32 --fcompiler=gfortran --f77flags="-fno-range-check"
Unknown vendor: "gfortran"
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "helloworld_fortran" sources
f2py options: []
f2py:> c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\helloworld_fortranmodule.c
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7
Reading fortran codes...
        Reading file 'test.f' (format:fix,strict)
Post-processing...
        Block: helloworld_fortran
                        Block: greetings
Post-processing (stage 2)...
Building modules...
        Building module "helloworld_fortran"...
                Constructing wrapper function "greetings"...
                  greetings()
        Wrote C/API module "helloworld_fortran" to file "c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\helloworld_fortranmodule.c"
  adding 'c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\fortranobject.c' to sources.
  adding 'c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7' to include_dirs.
copying C:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\f2py\src\fortranobject.c -> c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7
copying C:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\f2py\src\fortranobject.h -> c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7
build_src: building npy-pkg config files
running build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize Gnu95FCompiler
Found executable C:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\bin\gfortran.exe
customize Gnu95FCompiler using build_ext
building 'helloworld_fortran' extension
compiling C sources
C compiler: gcc -O2 -Wall -Wstrict-prototypes

creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy
creating c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7
compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Ic:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7 -IC:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\core\include -IC:\Users\builder\AppData\Local\Temp\mc2\include -IC:\Users\builder\AppData\Local\Temp\mc2\PC -c'
gcc -O2 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Ic:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7 -IC:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\core\include -IC:\Users\builder\AppData\Local\Temp\mc2\include -IC:\Users\builder\AppData\Local\Temp\mc2\PC -c c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\fortranobject.c -o c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\fortranobject.o
gcc -O2 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Ic:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7 -IC:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\core\include -IC:\Users\builder\AppData\Local\Temp\mc2\include -IC:\Users\builder\AppData\Local\Temp\mc2\PC -c c:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\helloworld_fortranmodule.c -o c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\helloworld_fortranmodule.o
compiling Fortran sources
Fortran f77 compiler: C:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\bin\gfortran.exe -fno-range-check -O3 -funroll-loops
Fortran f90 compiler: C:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\bin\gfortran.exe -Wall -g -fno-second-underscore -O3 -funroll-loops
Fortran fix compiler: C:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\bin\gfortran.exe -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -O3 -funroll-loops
compile options: '-Ic:\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7 -IC:\Users\builder\AppData\Local\Temp\mc2\lib\site-packages\numpy\core\include -IC:\Users\builder\AppData\Local\Temp\mc2\include -IC:\Users\builder\AppData\Local\Temp\mc2\PC -c'
gfortran.exe:f77: test.f
C:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\bin\gfortran.exe -Wall -g -Wall -g -shared c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\helloworld_fortranmodule.o c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\users\builder\appdata\local\temp\tmpnjdcyy\src.win32-2.7\fortranobject.o c:\users\builder\appdata\local\temp\tmpnjdcyy\Release\test.o -LC:\Users\builder\AppData\Local\Temp\mc2\Library\mingw-w64\lib\gcc\i686-w64-mingw32\5.3.0 -LC:\Users\builder\AppData\Local\Temp\mc2\libs -LC:\Users\builder\AppData\Local\Temp\mc2\PCbuild -LC:\Users\builder\AppData\Local\Temp\mc2\PC\VS9.0 -lpython27 -lgfortran -o .\helloworld_fortran.pyd
Removing build directory c:\users\builder\appdata\local\temp\tmpnjdcyy
```

Run it:

```
python -c "from helloworld_fortran import greetings; greetings()"
```

.. you should see:

```
python -c "from helloworld_fortran import greetings; greetings()"
 Hello, world! I am Fortran!
```

**Comment by mingwandroid** [comment]
Closing again!
