### ISSUE TITLE
No way to change miniscule font size in Anaconda Navigator?

### ISSUE THREAD

**Issue by ahnugent** [ContinuumIO/anaconda-issues#947]
I just opened Navigator on my new Dell XPS 15 laptop (3840 x 2160 px screen), and the font is too small to read without a magnifying glass. There is no "view" menu, and Ctrl+ has no effect.

Is this an oversight, or is there a hidden trick to bump up the font size?

**Comment by goanpeca** [comment]
@ahnugent, Qt4 (the Graphical toolkit we use) for Navigator has problems handling high resolution screens. This problem has been fixed but conda official Qt5 packages are not yet available, but will be soon.

**Comment by ahnugent** [comment]
Thanks for the advice!

**Comment by paviomuniz** [comment]
I just have the similar problem, but with bigger font size in my dell desktop.

**Comment by kremens** [comment]
This is still a problem 4.5 years later. Everywhere you go on Github people are too eager to close issues...

**Comment by kremens** [comment]
Still a problem 4.5 years later.
